### ISSUE TITLE
 Cannot find name 'UploadFile'. and : Cannot find name 'UploadEvent'. in component

### ISSUE THREAD

**Issue by NikhilRadadiya** [georgipeltekov/ngx-file-drop#10]
I'm trying to use this but getting this error in my component where I added as per demo 
```public files: UploadFile[] = []; ```

M I missing something?

**Comment by georgipeltekov** [comment]
Hi,

try importing them by adding this line:
import { UploadFile, UploadEvent } from 'ngx-file-drop/lib/ngx-drop';

**Comment by NikhilRadadiya** [comment]
Okay, Thank you so much for your reply.
I get rid of the errors, 
by importing like this ```ngx-file-drop/lib/ngx-drop``` will have any impact when I do `aot` compilation?

**Comment by georgipeltekov** [comment]
Happy to know that it is fixed. Please try it with aot and  if there are any problems, please feel free to open new defect

**Comment by NikhilRadadiya** [comment]
Great! to have this kind of speedy support.
Thank you very much again.
