### ISSUE TITLE
Error: Cannot find name 'USVString'

### ISSUE THREAD

**Issue by nh-sinsit** [georgipeltekov/ngx-file-drop#101]
When used with Angular 7

ERROR in node_modules/ngx-file-drop/src/lib/ngx-drop/dom.types.d.ts(25,12): error TS2304: Cannot find name 'USVString'.
node_modules/ngx-file-drop/src/lib/ngx-drop/dom.types.d.ts(31,12): error TS2304: Cannot find name 'USVString'.

**Comment by georgipeltekov** [comment]
did you use the latest version 5.0.0?

**Comment by nh-sinsit** [comment]
Yes!

**Comment by georgipeltekov** [comment]
try deleting node_modules , run npm install and try again, or at least provide stackblitz example. 
In this one:
https://stackblitz.com/edit/angular-aleydx

you will see that the latest version works fine with angular 7.
