### ISSUE TITLE
New 5.0.0 version not available from Sonatype Nexus 

### ISSUE THREAD

**Issue by guinnberg** [georgipeltekov/ngx-file-drop#102]
Trying to get the latest version via Nexus repository will fail with:
`verbose stack ngx-file-drop: No matching version found for ngx-file-drop@5.0.0`

Might this be due to the lack of a tag for this version?

**Comment by georgipeltekov** [comment]
tag is added. as this version was released today, probably it requires some time for this repo to be updated. Frankly , I dont use it and I am not familiar with it. From npm the version is up to date
