### ISSUE TITLE
Is it possible to get the full filepath for a dropped file?

### ISSUE THREAD

**Issue by nickraphael** [georgipeltekov/ngx-file-drop#104]
There is a property called fullPath.  But it does not give me the full path.  If I drag a file from c:/myDir/test.csv.   Then the fullPath is returned as /test.csv.   Is it possible to get the complete file path?

**Comment by georgipeltekov** [comment]
unfortunately no :( . This is not allowed by the html5 file api due to security restrictions.

**Comment by nickraphael** [comment]
I suspected that
