### ISSUE TITLE
Trying to implement ngx-file-drop in Angular lib

### ISSUE THREAD

**Issue by josefnorlin** [georgipeltekov/ngx-file-drop#106]
Hi,

I'm trying to include ngx-file-drop in my library but when trying to get the library's component css in my logotype-dialog.component.css it doesn't work:

.filedrop {
  .drop-zone {
    height: 100% !important;
  }
}

It does work if I put it in the app's styles.css as you explained here (https://github.com/georgipeltekov/ngx-file-drop/issues/21) but that doesn't work when I try using it in a library. So I'd like a way to specify a specific css file or component's css. Am I missing something? Can it be achieved?

**Comment by georgipeltekov** [comment]
Can you put the custom style as a property to the library, so the user who will use it can override it.
I am not sure that I understand exactly the use case, so a stackblitz example will be useful here

**Comment by josefnorlin** [comment]
Thanks for answering. Here's a stackblitz (not runnable though): https://stackblitz.com/edit/angular-lptppp 
In this project I have an app just for testing but the lib is what we aim to use.

The end user doesn't need to be able to edit the css, but I need to be able to do it inside the lib (located at "/projects/logotyphantering-lib/src/lib/") so that it works nicely without the end user having to edit their styles.css in their app. I therefore aim to change /projects/logotyphantering-lib/src/lib/logotype-dialog/logotype-dialog.component.scss instead of the styles.css. 

Hope that explained my use case better.

**Comment by georgipeltekov** [comment]
hmm, can you make it runnable? Otherwise I cannot do much. but in your lib you should have global css styles that is applied, have you?

**Comment by josefnorlin** [comment]
Nope, and that solved it! Or just a ::ng-deep on my ::ng-deep .filedrop { ... } in one of the components. Thank you sir!
