### ISSUE TITLE
file drag mouse over content flicker

### ISSUE THREAD

**Issue by angelayanpan** [georgipeltekov/ngx-file-drop#107]
https://angular-nuu2cz.stackblitz.io

https://stackblitz.com/edit/angular-nuu2cz

I took one of the stackblitz you created for another issue.  As user drag file to the target area and **move around near/over the Upload icon**, the content flickers a lot. 

Since i'm using a default background and using another color for the ".over" class, the flicker is very obvious in my app. 

I explored whether *ngIf is the culprit here. And tried to use the [hidden] alternative, I still see the flickering. Also tried switching the font awesome icon to just a label tag.  I still see the flickering.

Any help is appreciated.

**Comment by georgipeltekov** [comment]
The problem here is that in html5 the dragleave event is fired when going over child elements. Here you can check several options how to solve that:
https://stackoverflow.com/questions/7110353/html5-dragleave-fired-when-hovering-a-child-element

**Comment by angelayanpan** [comment]
@georgipeltekov  I tried wrapping the div in an Id and removed the pointer events.  It doesn't resolve the issue. 

#child * {
    pointer-events: none;
    background: hotpink;
}
