### ISSUE TITLE
How to retrieve all the header names of an uploaded csv file

### ISSUE THREAD

**Issue by arunkumaraithu** [georgipeltekov/ngx-file-drop#108]
I am Using angular 5.2 and I want to retrieve all the headers of an uploaded file. how to do it.

**Comment by georgipeltekov** [comment]
what do you mean under  the "headers of the file".
Did you check the readme? There is an console.log, that prints the file info.
You can check also this:
https://stackblitz.com/edit/angular-nuu2cz
