### ISSUE TITLE
ngx-file-drop not working for Firefox

### ISSUE THREAD

**Issue by praveen33in** [georgipeltekov/ngx-file-drop#11]
ngx-file-drop is not working in Firefox, its working in Chrome and Edge though. When I drag and drop a file, it is opening up in the browser window.

**Comment by georgipeltekov** [comment]
Can you check whether it is reproducible in the demo page as well. I just tried it in firefox and it seems to work fine

**Comment by praveen33in** [comment]
in Firefox, tt is not working in Demo page as well..

**Comment by georgipeltekov** [comment]
Can you try with the latest version (55.0.3)

**Comment by praveen33in** [comment]
With current version of Firefox, when i tried drag and drop of same file in this Comment area of Git Hub there is no issue, so i guess there is no issue with Firefox.

**Comment by georgipeltekov** [comment]
I tried with the latest version of the firefox and it is working fine.

**Comment by praveen33in** [comment]
That bad.... I think i might not be able to use "ngx-file-drop" then.... I won't be able to force application users to upgrade Firefox.
