### ISSUE TITLE
How to disable directory drag and drop?

### ISSUE THREAD

**Issue by gschauhan** [georgipeltekov/ngx-file-drop#114]
I need to disable directory drag and drop. User should not be able to drags and drops directory (Empty or not). Although they can select multiple files for drag and drop, but not the directory.

`public dropped(event: UploadEvent,concept,assetType) {     
    for (const droppedFile of event.files) {`
[https://imgur.com/a/nc08cWf](https://imgur.com/a/nc08cWf)
In above code, when i see in event variable, i am not able to determine if directory is dropped on dropzone or files, all i get is lit of array. How do determine if it is directory or not? Ultimately I need to disable directory drag and drop.

**Comment by georgipeltekov** [comment]
Did you check the readme file and the documentation how to use the lib? In it there is an example, showing  how to check whether the item is a file or folder (in the Usage -> Enabling File Drag section)

**Comment by gschauhan** [comment]
> Did you check the readme file and the documentation how to use the lib? In it there is an example, showing how to check whether the item is a file or folder (in the Usage -> Enabling File Drag section)

yes i did. Just checked again.
As expected, if i drop directory, 
`else {
        // It was a directory (empty directories are added, otherwise only files)
        const fileEntry = droppedFile.fileEntry as FileSystemDirectoryEntry;
        console.log(droppedFile.relativePath, fileEntry);
      }`
This section of your code example should be executed. It never comes here. 
`droppedFile.fileEntry.isFile` is always true.
