### ISSUE TITLE
Unit test component implementing ngx-file-drop

### ISSUE THREAD

**Issue by oscarbergstrom** [georgipeltekov/ngx-file-drop#115]
Hi,

I was wondering if there are any examples of how to unit test filedrop?

**Comment by georgipeltekov** [comment]
No, there are no examples. This is also depends actually on what are you going to test exactly

**Comment by fergardi** [comment]
Hello. I'm trying to accomplish a unit test as well, but with no luck so far.

What I'm trying to do is to mock a fake File being generated by hand and inserted into my component to test if has been created. To do so, I made a custom class:
```
class DropFileEventMock {
  files: NgxFileDropEntry[] = new Array<NgxFileDropEntry>()
  constructor() {
    let drop = this.createDrop()
    this.files.push(drop)
  }
  private createDrop(): NgxFileDropEntry {
    let file: FileSystemFileEntry = {
      isFile: true,
      isDirectory: false,
      name: null,
      file: () => createFile()
    }
    return new NgxFileDropEntry('', file)
  }
  public getFiles() {
    return this.files
  }
}
```
 With a custom fake File function as well:
```
function createFile(name: string = 'test.xlsx', type: string = 'application/vnd.ms-excel'): File {
  var blob = new Blob([''], { type: type })
  blob['lastModifiedDate'] = null
  blob['name'] = name
  return <File>blob
}
```
My component function does this (and works):
```
dropFile($event: any) {
    this.error = null
    this.file = null
    for (const droppedFile of $event) {
        if (droppedFile.fileEntry.isFile) {
            const fileEntry = droppedFile.fileEntry as FileSystemFileEntry
            fileEntry.file((file: File) => { // <-- this is the line I'm trying to fake
                this.file = file
            })
        }
    }
}
```
And then my test case looks like this:
```
it('should select the FILE by dropfile selector', () => {
    let file = createFile()
    const $event = new DropFileEventMock()
    component.dropFile($event.getFiles())
    expect(component.file).toEqual(file) // <-- this gives Error: Expected null to equal [object Blob]
  })
```
But my fake file is allways null. What I dont understand (and I need to in order to mock my fake file) is this callback:
```
const fakeFileEntry: FileSystemFileEntry = {
    name: (item as File).name,
    isDirectory: false,
    isFile: true,
    file: (callback: (filea: File) => void): void => { // <-- what does this callback do?
        callback(item as File);
    },
};
```
How do you call this callback? With which function? How can I create a fake FileSystemFileEntry?

Thanks in advance.

**Comment by fergardi** [comment]
@georgipeltekov nevermind, reading your source files I was able to mock a fake File:
```
const fakeFileEntry: FileSystemFileEntry = {
    name: 'test',
    isDirectory: false,
    isFile: true,
    file: (callback: (filea: File) => void): void => { // <-- what does this callback do?
        callback(createFile() as File) // <-- here I call my own function
    },
}
```
Thanks anyway.

**Comment by denn031** [comment]
You could try something like this `
      const file = new File([], 'badFile.csv');
      const fakeDrag = new DataTransferItemList();
      fakeDrag.add(file);
      const fakeFileEntry: FileSystemFileEntry = {
        name: file.name,
        isDirectory: false,
        isFile: true,
        file: <T>(callback: (filea: File) => T) => callback(file as File),
      };
      const fakeDrop: NgxFileDropEntry[] = [new NgxFileDropEntry(fakeFileEntry.name, fakeFileEntry)];`
