### ISSUE TITLE
Parameter [Clickable] ? 

### ISSUE THREAD

**Issue by Tang8** [georgipeltekov/ngx-file-drop#117]
Hello,

I'm asking a question about this component because i need to open Browser when i click in the dropzone ? 
Is it possible or i need to use another dropzone Component ?

Thanks for read this.

**Comment by georgipeltekov** [comment]
There is nothing specific about that. Basically you can add input type="file"  in the file-drop directive and customize the button the way you want. There are plenty of examples in the net, how the input file type could be customized.

**Comment by Tang8** [comment]
PS : I used your component in order to getting all files recursively in my folder.

**Comment by georgipeltekov** [comment]
Ahh now I think I get it. So you want to take every subfolders/files recursively, not only by dropping the files/folders, but also by having an input type button inside the dropzone? Unfortunately this is not supported.

**Comment by Tang8** [comment]
OK. Thanks i will do another button for getting all subitems.
