### ISSUE TITLE
Error: event is not defined

### ISSUE THREAD

**Issue by Garbanas** [georgipeltekov/ngx-file-drop#119]
A bug has been introduced with version 5.0.2 in `file-drop.component.ts` at line 136.
`this.preventAndStop(event);` has no variable `event` since it's not passed into `checkFiles()` which causes Firefox to break (Chrome seems fine).

**Comment by georgipeltekov** [comment]
Sorry about that, I just publish version 5.0.3

**Comment by Garbanas** [comment]
I just made some changes myself in case you want to merge them: https://github.com/georgipeltekov/ngx-file-drop/pull/120
