### ISSUE TITLE
Example on how to make this "post" the file

### ISSUE THREAD

**Issue by the7erm** [georgipeltekov/ngx-file-drop#12]
This works great, however I'm at a loss. How do you get this thing to actually post the file to the server?

Would you mind including an example?

**Comment by georgipeltekov** [comment]
It depends where you are uploading the file. For instance you can use:
let body = new FormData();
        body.append('file', data);
        return this.http.post(url, body, {
            headers: headers
        });
where data is UploadFile.file property

**Comment by the7erm** [comment]
Thanks.
