### ISSUE TITLE
Ability to add the browse files event to our own items

### ISSUE THREAD

**Issue by Nxt3** [georgipeltekov/ngx-file-drop#122]
If we have custom content in the drop area, I'd like to be able to place the "Browse click" on any item I want.

Currently, I'm getting around this by doing something like:

```
public browseFiles(event: MouseEvent): void {
    const fileSelector: HTMLInputElement = document.querySelector("input[type='file']");
    fileSelector.click();
}
```

but that feels weird. Maybe placing a directive on an HTML element would enable the "Browse click" event to pass through to what you have?

**Comment by georgipeltekov** [comment]
I didnt quite get your point. Is the latest updates, with adding custom imput type button solve your issue?

**Comment by Nxt3** [comment]
No because that only allows us to style a button. What if we wanted an `<a>` tag to initiate the browse action? We can't do that without doing something like I've outlined above.

I'm proposing creating a directive that when placed on an element, imbues the properties necessary for handling this.

**Comment by Garbanas** [comment]
Hey @Nxt3 
You should be able to use the public method `onBrowseButtonClick` of `FileComponent` for your purpose.

```
<file-drop #myFileDrop>
  <button (click)="myFileDrop.onBrowseButtonClick($event)">My custom button</button>
</file-drop>
```

This is untested and I wrote this just from the top of my head. Proceed with caution :)

**Comment by Nxt3** [comment]
@Garbanas I guess that's good enough.
