### ISSUE TITLE
custom styles

### ISSUE THREAD

**Issue by sante85** [georgipeltekov/ngx-file-drop#126]
how to inject my scss to component??

.drop-zone1 {
    margin: auto !important;
    height: 100px !important;
    border: 2px dashed #5c5b5b !important;
    border-radius: 18px !important;

    display: -ms-flexbox !important;
    display: -webkit-flex !important;
    display: flex !important;
    -webkit-flex-direction: column !important;
    -ms-flex-direction: column !important;
    flex-direction: column !important;
    -webkit-flex-wrap: nowrap !important;
    -ms-flex-wrap: nowrap !important;
    flex-wrap: nowrap !important;
    -webkit-justify-content: center !important;
    -ms-flex-pack: center !important;
    justify-content: center !important;
    -webkit-align-content: center !important;
    -ms-flex-line-pack: center !important;
    align-content: center !important;
    -webkit-align-items: center !important;
    -ms-flex-align: center !important;
    align-items: center !important;
  }

  .content1 {
    -webkit-order: 0 !important;
    -ms-flex-order: 0 !important;
    order: 0 !important;
    -webkit-flex: 0 1 auto !important;
    -ms-flex: 0 1 auto !important;
    flex: 0 1 auto !important;
    -webkit-align-self: center !important;
    -ms-flex-item-align: center !important;
    align-self: center !important;
  }

 <file-drop customstyle="drop-zone1" customContentStyle="content1" headertext="Trascina qui" (onFileDrop)="dropped($event)"
             (onFileOver)="fileOver($event)" (onFileLeave)="fileLeave($event)">
    <span></span>
  </file-drop>

**Comment by georgipeltekov** [comment]
you need t define that class in the global css  (#21 )
