### ISSUE TITLE
Bug with filedrop event

### ISSUE THREAD

**Issue by ChaitanyaKN** [georgipeltekov/ngx-file-drop#128]
I am facing an issue with the  FileDrop event, So the issue goes like this:

1. I **browse for a  file**(using the browse files button) named XYZ.pdf, and the FileDrop event is raised, one of my methods is called and it populates an array with the files dropped. 
2. I browse for the exact same file again(using the browse files button) immediately, but this time the FileDrop event is not called. 

This issue occurs **only** when i am using the browse files button during either the first time i am uploading or the second time. It works **perfectly if i use drag&drop both times**.
The only "workaround" is that I should not upload the same set of files in consecutive tries. If I upload some other file, it works. And then I can upload the original set again.

Is this an intended functionality or a bug?

**Comment by georgipeltekov** [comment]
Hi,

this is the default behavior of HTML input type file attribute. There are several workarounds in the web, that you can try and see, if it will fits your need
