### ISSUE TITLE
Compile .js and .js.map files

### ISSUE THREAD

**Issue by Arathmorr** [georgipeltekov/ngx-file-drop#13]
I'm trying to use this in an Ionic app but when I run it I get 
`Uncaught Error: Module build failed: Error: ENOENT: no such file or directory, open '/path/to/ngx-file-drop/lib/ngx-drop/index.js.map'`

Is there anything I can tweak in tsconfig.json to get it to generate these two files? I've tried building it but no luck.
Thanks.

**Comment by georgipeltekov** [comment]
Hey,

I just added new version with dist folder. In it you can find the .js and the .js.map files

**Comment by Arathmorr** [comment]
`webpackJsonp is not defined` error.

The demo on https://npm.runkit.com/ngx-file-drop no longer runs either by the way, could be related to this latest change.

**Comment by georgipeltekov** [comment]
The demo in the library itself seems to work. If you get the source code and run ng serve it should work as expected.  Also  I am not sure how you import the reference to the library.  There is some useful information in this thread:
https://github.com/webpack/webpack/issues/368

**Comment by Arathmorr** [comment]
Thanks for your help. Still no luck but I feel it is now more to do with how the project I'm working on is structured rather than any more issues with the plugin. I'll keep working on it, but regardless thank you very much for your support.
