### ISSUE TITLE
Upload same file (using browse) won't work

### ISSUE THREAD

**Issue by Inexad** [georgipeltekov/ngx-file-drop#134]
When i choose a file using browse button it calls the "onFileDrop"-event. When choosing the same file again then "onFileDrop"-event does not get called. 

Using Angular 7 and this code:

```
 <file-drop headertext="Drop files here " (onFileDrop)="uploadAttachment($event)"
               (onFileOver)="fileOver($event)" (onFileLeave)="fileLeave($event)" showBrowseBtn="true" browseBtnLabel="or click to browse files">
    </file-drop>
```

**Comment by georgipeltekov** [comment]
did you check with the latest version (6.0.0)

**Comment by Inexad** [comment]
I updated to latest version now and it works! Thanks.
