### ISSUE TITLE
New window for file being opened in Firefox

### ISSUE THREAD

**Issue by joecollett** [georgipeltekov/ngx-file-drop#135]
I'm currently on the latest version of Firefox (65.0.2 - 64 bit). I've tested this within my app and your demo application. On both counts when I drag and drop a file into the dropzone the file opens inside the browser. While in chrome it will correctly add the file to table.

![image](https://user-images.githubusercontent.com/13499326/54549177-726fc280-49a1-11e9-9fde-5df77b989f3c.png)

**Comment by georgipeltekov** [comment]
Hi,

it seems to be something specific with your firefox version and/or configurations. I just tried with 66.0 (64 bit) with this example:
https://angular-blhb9x.stackblitz.io

dropping jpg and png files and it seems to work just fine

**Comment by joecollett** [comment]
Could you make the code accessible for that stackblitz? As that works fine but your demo here https://georgipeltekov.github.io/ doesnt work. Would be greatly appreciated as dont understand why one is working and why the other isnt.

**Comment by georgipeltekov** [comment]
You need just to change the url:

https://stackblitz.com/edit/angular-blhb9x
