### ISSUE TITLE
file-drop is not a known element

### ISSUE THREAD

**Issue by brandonburns** [georgipeltekov/ngx-file-drop#136]
I have seen your previous responses to this, but this is still happening for me. I am using angular 6. I have tried all versions 4.0.0 - 4.0.6 which claim to be for Angular 6. I made sure the ^ was removed from package json. I have deleted node_modules and ran npm install multiple times. Still has the same error in the console, file-drop is not a known element

I have FileDropModule imported into my module, and included in my imports, just as the docs show

**Comment by georgipeltekov** [comment]
Can you please give a stackblitz example with your configurations?

**Comment by georgipeltekov** [comment]
Here you can see working example with angular 6 and nxg-file-drop 4.0.6
https://stackblitz.com/edit/angular-nul7y6
