### ISSUE TITLE
accept parameter not working

### ISSUE THREAD

**Issue by AbhijeetGiram** [georgipeltekov/ngx-file-drop#137]
I am using this in angular 6. I want to restrict file format for "png" only. But it is not working.
accept | String of accepted formats | accept="png"

<file-drop dropZoneLabel="Drag and drop your files anywhere or" (onFileDrop)="dropped($event)"
             (onFileOver)="fileOver($event)" (onFileLeave)="fileLeave($event)" accept="png">
  </file-drop>

Need help.

**Comment by georgipeltekov** [comment]
what version of the library are you using?

**Comment by AbhijeetGiram** [comment]
"ngx-file-drop": "^6.0.0",

**Comment by georgipeltekov** [comment]
accept is the html 5 attribute. You can check the compatibility table here:
https://caniuse.com/#feat=input-file-accept

Also, you have to specify "image/png".

You can check this link:
https://stackoverflow.com/questions/3828554/how-to-allow-input-type-file-to-accept-only-image-files/15857189
