### ISSUE TITLE
Plan for showBrowseFolderBtn?

### ISSUE THREAD

**Issue by cdibbs** [georgipeltekov/ngx-file-drop#140]
I want my users to be able to upload either a zip or a directory (which my code might zip in .js). Is there a way to show a second button that could let them pick a directory? Right now, they could only drag-and-drop a folder, is that correct?

Thank you!

**Comment by georgipeltekov** [comment]
Frankly, I dont understand what you mean under directory and folder, for me it is the same. You can drag files and folders and you can also restrict them by their type (if you like to drag and drop only zips for instance)

**Comment by cdibbs** [comment]
Hi, thanks for your quick reply. Yes, you can drag and drop both files and folders just fine. However, in order to pick a folder using the button, the `input` tag would have to have a particular attribute (`directory` or `webkitdirectory`).

Anyway, not long after opening this issue, I realized I wanted something pretty custom, so I ended up "rolling my own." So, feel free to disregard this request unless you feel it would be helpful to others.

Thanks, again!
