### ISSUE TITLE
Start upload window on click

### ISSUE THREAD

**Issue by NilsMinor** [georgipeltekov/ngx-file-drop#148]
Hi,
is it possible to start an upload window to select files to upload by clicking on the drag & drop area?

best regards,
Nils

**Comment by georgipeltekov** [comment]
Did you check the the showBrowseBtn option? If you dont want to have a visible button you can hide it with css and make trigger its clicking

**Comment by NilsMinor** [comment]
Hi,
yes I checked the showBrowseBtn option. I would like to start folder upload by clicking on the Dropzone. Is there a way to call the "**onBrowseButtonClick**" from my component / my click handler?

**Comment by georgipeltekov** [comment]
What I can think of is to have (click) in the file-drop directive, calling a function in the angular. And from there with elementref find the input element and call its click()
