### ISSUE TITLE
Allow ngx-file-drop on systems having Node < 12

### ISSUE THREAD

**Issue by GregOnNet** [georgipeltekov/ngx-file-drop#152]
Hi,

thank you for providing this library. 🎉
It helps us a lot.

We use Node 10. Installing `ngx-file-drop` with yarn causes an error, due to Node version restrictions in [package.json](https://github.com/georgipeltekov/ngx-file-drop/blob/master/package.json#L4):

```
error ngx-file-drop@8.0.0: The engine "node" is incompatible with this module. Expected version ">= 12.0.0". Got "10.15.3"
```

## Request

Is it possible to tolerate Node versions higher than 10?

## Workaround

You still can install the newest version of `ngx-file-drop` running `yarn install --ignore-engines`.

**Comment by Garbanas** [comment]
Hi @GregOnNet 

Angular 8, the current latest version of Angular, requires Node 12 or later. With the last update of ngx-file-drop for Angular 8 the version requirement for Node has been raised as well.

**Comment by GregOnNet** [comment]
I see,

thanks for the quick answer. 👍 
We will update our build agents accordingly. 🙂

**Comment by mudcrab** [comment]
@Garbanas Angular 8 supports latest Node LTS just fine, can you maybe tune the engines part of your library according to Angular's support?

For instance, [Angular update guide](https://update.angular.io/#7.2:8.0) suggests Node 10 or higher and Angular and Angular CLI repos have both specified 10.9 as minimal version.

**Comment by Garbanas** [comment]
@mudcrab Huh. You're correct. I could have sworn that when I ran the update guide ~25 days ago that Node 12 was required. Of course the requirement can be lowered, no problem there 👍

**Comment by mudcrab** [comment]
Thank you! 👍

**Comment by vanstinator** [comment]
Looks like the 8.0.3 _package_ is still requiring node >= 12.0.0

**Comment by alignsoft** [comment]
I'm finding the same issue as @vanstinator with 8.0.3

`error ngx-file-drop@8.0.3: The engine "node" is incompatible with this module. Expected version ">= 12.0.0". Got "10.16.0"`

**Comment by chrismclarke** [comment]
Yeah if you could bump the npm version to reflect the changes that would be amazing. Thanks again for the awesome repo!

**Comment by georgipeltekov** [comment]
check 8.0.4

**Comment by vanstinator** [comment]
Thank you!

**Comment by chrismclarke** [comment]
confirmed working, thank you very much again
