### ISSUE TITLE
Readme example is not working

### ISSUE THREAD

**Issue by swftvsn** [georgipeltekov/ngx-file-drop#154]
I had to add `ngx-file-drop-content-tmp` to the `ng-template` to get custom template working. Am I doing something wrong or is the readme out of date?

Basically I have
```
<ngx-file-drop #drop *ngFor="let category of categoriesObservable | async" dropZoneClassName="cat-container"
        [class.chosen-cat]="category.chosen && !isDragging"
        (click)="chooseCategory(category)"
        (onFileOver) ="fileOver ($event, category)"
        (onFileDrop) ="fileDrop ($event, category)"
        (onFileLeave)="fileLeave($event, category)"
        class="drop"
>
  <ng-template ngx-file-drop-content-tmp>
    <div>
      <img [src]="category.image | async"
        [class.light-gray-background]="(!category.chosen && !isDragging) || (!drop.dragoverflag && isDragging)"
        [class.light-blue-background]="( category.chosen && !isDragging) || ( drop.dragoverflag && isDragging)"
      />
    </div>
  </ng-template>
<ngx-file-drop
```

**Comment by Garbanas** [comment]
Hi @swftvsn 

1. What is `isDragging` referring to? It it's referring to the internal property of NgxFileDropComponent, then that property has been renamed to `globalDraggingInProgress` and is now private...
2. The property `dragoverflag` has been renamed to `isDraggingOverDropZone`

Apart from that (filling in some gaps) your example seems to work just fine.

**Comment by georgipeltekov** [comment]
in 8.0.3 ngx-file-drop-content-tmp is added, so it should be ok now

**Comment by swftvsn** [comment]
isDragging is our own variable. Thanks for pointing out the renamed flag. The question was specifically about the readme missing `ngx-file-drop-content-tmp`, which is there now. Thank you for that too.
