### ISSUE TITLE
Unable to get Custom content to work

### ISSUE THREAD

**Issue by soeberg84** [georgipeltekov/ngx-file-drop#156]
Hi,

I have just upgraded to angular 8 with the latest ngx-file-drop and i am unable to get the custom content to work.
I have copied the example code into stackblitz:

https://stackblitz.com/edit/angular-n7nhbs

_"Optional custom content that replaces the the entire default content."_ is not shown anywhere.

I think the text and a button should be shown, yes? :)

Or what am I missing?

Regards
Martin

**Comment by soeberg84** [comment]
[Possible clone](https://github.com/georgipeltekov/ngx-file-drop/issues/154)

**Comment by georgipeltekov** [comment]
Does the fix in #154 works for you?

**Comment by andyer01** [comment]
hi, i get same issue, if you fixed, please share with me, thanks

**Comment by soeberg84** [comment]
I fixed by applying "ngx-file-drop-content-tmp" to ng-template.
<ng-template ngx-file-drop-content-tmp>
 <div class="drop-content">
--> My content
      </div>
</ng-template>

And my styling looks like this:


::ng-deep .drop-content {
  display: flex;
  justify-content: space-between;
  flex-direction: column;
  align-items: center;
  color: $seges-dark;
  height: 120px;
}

::ng-deep .my-dropzone-style {
  border-radius: 0px !important;
  border: 3px dotted $seges-dark !important;
  height: 300px !important;
  display: flex;
  justify-content: center;
  align-items: center;
}

**Comment by georgipeltekov** [comment]
@andyer01 did you check the  fix in #154
