### ISSUE TITLE
[accept] and [multiple] are not working.

### ISSUE THREAD

**Issue by popoleeMaster** [georgipeltekov/ngx-file-drop#157]
So, I have seen there is a lot of issue like this in the list of issue but.

I am using 6.0.1 I have a default upload component (that use ngx-file-drop but also handle file explorer...)

my component is called 

`<app-file-upload [formats]="'.csv'" [multiple]="false"></app-file-upload>`

then inside my component I have 

template => 
```
  <file-drop dropZoneLabel="{{files[0]?.relativePath || 'No File'}}"
  (onFileDrop)="dropped($event)"
  (onFileOver)="fileOver($event)"
  (onFileLeave)="fileLeave($event)"
  [accept]="formats"
  [multiple]="multiple">
```

component => 
```
  @Input() formats: string;
  @Input() multiple: boolean;
```

never working, I also changed multiple to a string, and formats to like text/csv, always same behaviour, everything is accepted, no filtering.

I ended up adding my custom checking and removing everything by myself.

Is it me that don't understand or it is just not working ?

**Comment by georgipeltekov** [comment]
You can check this stackblitz:
https://stackblitz.com/edit/angular-blhb9x

(you can select only images from the browse button)
as multiple and accept are attributes from html5 input field they are working only for the input button, not for the dropping option.

**Comment by popoleeMaster** [comment]
ah, ok, I thougt you already implements some guard in the library about for the drop.

**Comment by mwunderlich** [comment]
Why was this issue closed? It seems the accept attribute is still not working in the ngx-file-drop component when dropping files.

**Comment by bchehraz** [comment]
I'm having to create my own solution for this particular issue by checking if certain conditions are met and presenting some custom error response, I am testing the conditions within the `drop` function, not `fileOver` or `fileLeave` since I'm trying to enforce 1 file at a time and the drag n drop still accepts multiple if multiple=false
