### ISSUE TITLE
disable browse button

### ISSUE THREAD

**Issue by tassin-gauthier** [georgipeltekov/ngx-file-drop#159]
Is it possible to disable or override the browse button ? I use a library for my own browse button with a style and particular behavior.

The only option i found is to apply a class on the default button with the attribute browseBtnClassName, hide it, then put my own button and redirect the click on the default hidden button. It works well but that's not really clean.

 Thanks.

**Comment by georgipeltekov** [comment]
Did you check the showBrowseBtn property, described in the readme?

**Comment by tassin-gauthier** [comment]
I noticed that but the problem is this option completely disable the button when i just want to use the functionality of this default button with my own button and i can't link it to the file-drop (except the dirty method i described)

**Comment by georgipeltekov** [comment]
with browseBtnClassName you can style the button in the way you want it, as you did. However if you want something more specific from functional point of view, the way you described it is the right way to do it. This is way too specific.
