### ISSUE TITLE
Published NPM package still has node >=12

### ISSUE THREAD

**Issue by cdumas22** [georgipeltekov/ngx-file-drop#160]
The published version on npm version 8.0.3 still has a requirement on node >=12

  "$schema": "../node_modules/ng-packagr/package.schema.json",
  "name": "ngx-file-drop",
  "version": "8.0.3",
  "description": "Angular ngx-file-drop - Simple desktop file and folder drag and drop",
  "author": "Georgi Peltekov",
  "license": "MIT",
  "repository": "georgipeltekov/ngx-file-drop",
  "engines": {
    "node": ">= 12.0.0",
    "npm": ">= 6.9.0"
  },

**Comment by georgipeltekov** [comment]
#152
