### ISSUE TITLE
How do I accept multiple type of files?

### ISSUE THREAD

**Issue by frabanca** [georgipeltekov/ngx-file-drop#161]
For example, what should I write in "accept" to accept xlsx, xls and csv only?
Thanks :)

**Comment by georgipeltekov** [comment]
The accept parameter just use the standard html 5 functionality. For excel file formats you can check here:
https://stackoverflow.com/questions/11832930/html-input-file-accept-attribute-file-type-csv

**Comment by frabanca** [comment]
Great, thanks! 👍
