### ISSUE TITLE
Angular version 8 updated, ran Yarn install and error of ngx-file-drop@8.0.4 is keep happening

### ISSUE THREAD

**Issue by jayDesai89** [georgipeltekov/ngx-file-drop#162]
package.json
`{
  "name": "angular",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.0.1",
    "@angular/cdk": "github:angular/cdk-builds",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/http": "~7.2.15",
    "@angular/material": "github:angular/material2-builds",
    "@angular/material-moment-adapter": "^7.0.4",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "@ng-bootstrap/ng-bootstrap": "^2.0.0",
    "@nguniversal/express-engine": "^8.1.1",
    "@types/highcharts": "^5.0.32",
    "HubModule": "git+https://isdr-package:856cfc5b6783723d095ee5b291b12f4e5e507e23@github.com/IssuerDirect/HubModule.git#alpha",
    "angular-file-uploader": "^4.2.1",
    "angular-froala-wysiwyg": "^2.8.4",
    "angular-sortablejs": "^2.6.0",
    "angular-webstorage-service": "^1.0.2",
    "angular2-csv": "^0.2.9",
    "bootstrap": "^4.1.3",
    "classlist.js": "^1.1.20150312",
    "compass-mixins": "^0.12.10",
    "core-js": "^2.4.1",
    "css-animation": "^1.4.1",
    "file-saver": "^2.0.2",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "highcharts": "^6.1.4",
    "highcharts-angular": "^2.3.1",
    "highcharts-custom-events": "^2.2.1",
    "jquery": "^3.3.1",
    "moment": "^2.24.0",
    "ng-multiselect-dropdown": "^0.2.3",
    "ng-sidebar": "^7.1.0",
    "ngx-bootstrap": "^3.1.3",
    "ngx-cookie": "^4.1.2",
    "ngx-file-drop": "^8.0.4",
    "ngx-popover": "^0.0.16",
    "ngx-spinner": "^8.0.3",
    "ngx-toastr": "^9.1.1",
    "ngx-ztk-csvexporter": "^1.0.3",
    "popper.js": "^1.14.4",
    "rxjs": "~6.4.0",
    "rxjs-compat": "~6.4.0",
    "sortablejs": "^1.7.0",
    "xlsx": "^0.14.3",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "~8.0.1",
    "@angular/compiler-cli": "~8.0.0",
    "@angular/language-service": "~8.0.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "axios": "^0.18.0",
    "codeceptjs": "^2.0.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "selenium-standalone": "^6.15.4",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~3.4.3",
    "webdriverio": "^5.4.17"
  }
}
`

error : 
`yarn run v1.6.0
error Command "update" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by georgipeltekov** [comment]
Frankly, I cannot understand what you ran and what is the error ( and if it connected with the library at all).
How did you suspect, that the problem is in ngx-file-drop?
