### ISSUE TITLE
Display file after Upload

### ISSUE THREAD

**Issue by Hspharwinder** [georgipeltekov/ngx-file-drop#164]
If you facing error of fileEntry.**file**((file:File)  then remove **FileSystemDirectoryEntry**  
 from
 `import { NgxFileDropEntry,FileSystemFileEntry, FileSystemDirectoryEntry } from 'ngx-file-drop';`
and keep `import { NgxFileDropEntry,FileSystemFileEntry } from 'ngx-file-drop';`

**Display image after uploading**
-------------------------------------------------
` public dropped(files: NgxFileDropEntry[]){

    this.filesStore = files; // fileStore using in DOM
    var reader = new FileReader(); // **for reading file**
    for(const droppedFile of files){
      // Is it a file?
      if(droppedFile.fileEntry.isFile){
        let fileEntry = droppedFile.fileEntry as FileSystemFileEntry;
        fileEntry.file((file:File) => {
          // Here you can access the real file
          console.log(droppedFile.relativePath, file);
          //Code for reading File
          reader.readAsDataURL(file);
            reader.onload = () => {
                this.imgUrl = reader.result;
            };
        });

         /**
          // You could upload it like this:
          const formData = new FormData()
          formData.append('logo', file, relativePath)

          // Headers
          const headers = new HttpHeaders({
            'security-token': 'mytoken'
          })

          this.http.post('https://mybackend.com/api/upload/sanitize-and-save-logo', formData, { headers: headers, responseType: 'blob' })
          .subscribe(data => {
            // Sanitized logo returned from backend
          })
          **/

      }else{
         // It was a directory (empty directories are added, otherwise only files)
        const fileEntry = droppedFile.fileEntry as FileSystemFileEntry;
        console.log(droppedFile.relativePath, fileEntry);
      }
    }
  }`

**In Dom Use like this.**
`<img [src]="imgUrl" height="100px"> `

**Comment by georgipeltekov** [comment]
you can check #36
