### ISSUE TITLE
openFileSelector() not working in 8.0.6

### ISSUE THREAD

**Issue by valentintintin** [georgipeltekov/ngx-file-drop#165]
Version
Upgrading from 8.0.3 to ^8.0.6

Steps to reproduce

```
<ngx-file-drop dropZoneLabel="Drop files here" (onFileDrop)="dropped($event)" 
    (onFileOver)="fileOver($event)" (onFileLeave)="fileLeave($event)">
        <ng-template ngx-file-drop-content-tmp let-openFileSelector="openFileSelector">
          Optional custom content that replaces the the entire default content.
          <button type="button" (click)="openFileSelector()">Browse Files</button>
        </ng-template>
</ngx-file-drop>
```
Alternate between v8.0.3 and 8.0.6.

Expected Behavior
Button should open file picker

Actual Behavior
In 8.0.6, the file picker does not display

**Comment by pdrakos** [comment]
same here. Upgraded from version 8.0.4 to 8.0.6 and sfile picker does not display.

**Comment by georgipeltekov** [comment]
sorry about that, it was regression. It is fixed in 8.0.7

**Comment by steveDL** [comment]
Hey, I am having this issue in version 11. If I drag an image in it works but the button wont open the file selector

**Comment by maiertudor** [comment]
@steveDL I experience the same thing on macOS
"ngx-file-drop": "^10.1.1"

**Comment by srivastavaanurag79** [comment]
openFileSelector() not working on `macOS v12.3`
`"ngx-file-drop": "^14.0.1",`
```
  "@angular/compiler": "14.1.3",
    "@angular/core": "14.1.3",
    "@angular/forms": "14.1.3",
    "@angular/localize": "^14.1.3",
    "@angular/platform-browser": "14.1.3",
    "@angular/platform-browser-dynamic": "14.1.3",
    "@angular/router": "14.1.3",
```
