### ISSUE TITLE
when using multiple file upload option.

### ISSUE THREAD

**Issue by Ambuj18** [georgipeltekov/ngx-file-drop#167]
Multiple upload work simultaneously but does not work independently

**Comment by georgipeltekov** [comment]
I am not sure I understand you, could you please elaborate on that a little bit more. Also a stackblitz example would be helpful

**Comment by Ambuj18** [comment]
okay see if i m using multiple file upload option. Than when i select multiple file at time it works.But when i select them  one at a time then files get replaced and last file isuploaded.

**Comment by georgipeltekov** [comment]
How do you handle the files coming from the library. Are you sure, that you are not using the same list, overriding it in your code?

**Comment by Ambuj18** [comment]
i am  trying to say that if files are available at two different folder than how multiple upload option will work.

**Comment by georgipeltekov** [comment]
First you will drag the file from the first folder, then you go and upload the second one. If you want some caching mechanism you can try to put the files in some queue and then pass it to the library

**Comment by Ambuj18** [comment]
okay thanks
