### ISSUE TITLE
Upload progress, Pause/Resume, Cancel?

### ISSUE THREAD

**Issue by haggins** [georgipeltekov/ngx-file-drop#169]
Hi,
we're currently using ngx-file-drop in a project. Now, we received new requirements:
Upload progress, pause/resume and cancel.

Are those possible with ngx-file-drop?

Thank you in advance.
Patrick

**Comment by georgipeltekov** [comment]
Hi,

no, this does not come from the library out of the box. Basically the user is responsible for uploading the file to the desired location ( could be cloud, server , etc. ) and during the upload implementation ( again depending on how and where the file needs to go) this cases should be handled
