### ISSUE TITLE
How do i not accept or ignore dropped directories and its contents

### ISSUE THREAD

**Issue by TomislavSmvc** [georgipeltekov/ngx-file-drop#172]
When i drag and drop a directory, then i get an item for every file in that directory. I would like to prevent that and only get items for files i drag in

**Comment by georgipeltekov** [comment]
Can you elaborate a little bit. So you are dropping a folder and you want to get only the files from this folder and ignore the subfolders and their content?

**Comment by TomislavSmvc** [comment]
This is the scenario i am talking about:

I select a file "Picture1.png" and a folder "pictures" and drag them into the ngx-file-drop component. In that case i want to ignore the folder "pictures" and everything in it and only accept "Picture1.png".

The reason: What if there are hundreds/thousands of files in that "pictures" folder.  Processing them all would be a bad idea.

**Comment by georgipeltekov** [comment]
Why are you dragging the folder at a first place, if you want to ignore it?
But still, you can check the type of the item and if it is a folder, just to skip it.

**Comment by TomislavSmvc** [comment]
Well, i cant controll the end user and he could accidentally drag in a folder with hundreds of files.

But i see it now, when you drag in a folder, for every file in the folder you get a item with the name "folder_name/file.name.txt". So i only need to check if the name contains a "/". Or is there a better way?

**Comment by georgipeltekov** [comment]
you can check also the standard isFile property from html 5 file api. In the example from the readme you can see how it is used.

**Comment by TomislavSmvc** [comment]
But i want to ignore files inside the dragged folders too, not just the folders themself. So im jzst gonna check the relative path for "/"
