### ISSUE TITLE
Can't collect all file Object together

### ISSUE THREAD

**Issue by dgraceffa** [georgipeltekov/ngx-file-drop#175]
Hi,
I found your library really usefull but i need to store all File object (the ones you get with callback)
in a single array to upload every file togheter. There is a way to do this?
Thanks

**Comment by georgipeltekov** [comment]
I am not sure I get you right, but can you just add the files to the array, after you get them from the callback (iterating the files as described in the read.me)?

**Comment by dgraceffa** [comment]
By doing this, the array will always be empty. Do you know a way to add the file from callback inside the forEach?

**Comment by georgipeltekov** [comment]
this is not related to the library, you can check plenty of google solutions, like this for instance:
https://logicmason.com/2019/how-to-access-this-from-inside-a-callback/

Also, I would suggest to start with the getting started section for the angular library or some online extended course, for better understanding the needed principles. It will help you and save a lot of time in the future.
