### ISSUE TITLE
Class NgxFileDropModule is not an Angular module.

### ISSUE THREAD

**Issue by HFTSOL** [georgipeltekov/ngx-file-drop#176]
PREFACE:  App builds, runs, and appears to work; so this is more of a note that there is an incompatibility or configuration issue rather than a show stopper.

NgxFD Version:  8.0.8
NG Version:  8.2.7
IDE: Webstorm

Steps:
- Install package: "npm i --save ngx-file-drop"
- Add import to top of app.module: "import {NgxFileDropModule} from 'ngx-file-drop';"
- Add NgxFileDropModule module to import list for module.

Result: 
- IDE shows red squiggly lines under NgxFileDropModule in the imports list and show error message "Class NgxFileDropModule is not an Angular module".
- Intellisense doesn't in the IDE for your interfaces, so they have to be manually imported.
- IDE cannot go to source of components as it sees them as _unknown HTML element tags_.

As stated, these are not show stoppers, but I figured you might want to know that there is some library creation configuration or something else that could be tweaked for better compatibility.

Other than that, thanks for making this kool tool.  Much appreciated.

**Comment by sagitarious12** [comment]
same thing happening here.

**Comment by ZaL0-0** [comment]
+1

**Comment by DianaCondon** [comment]
+1

**Comment by justinwilaby** [comment]
This is possibly related to: [this angular issue](https://github.com/angular/angular/issues/38893). I have a [minimal repro here](https://github.com/justinwilaby/angular-issue-no38893) using this library as the example. 

If this isn't fixed soon, I will be forced to remove this dependency in several production apps since it's the last item preventing us from updating to angular 10.

**Comment by georgipeltekov** [comment]
@justinwilaby  this issue is IDE related and it is not connected with Angular 10 support. The latest version of the library supports Angular 10

**Comment by justinwilaby** [comment]
@georgipeltekov - Please see the repro i posted. This library does not build when used as a dependency inside another angular library. Although this may be a separate issue, the ide may be using an angular plugin to generate this error.

**Comment by georgipeltekov** [comment]
you need to enable Ivy. 

`  "angularCompilerOptions": {
    "enableIvy": true
  }`

in tsconfig.js and your repo is building fine after that

**Comment by justinwilaby** [comment]
@georgipeltekov - This is a library project which the Angular documents [recommend against using the Ivy compiler](https://angular.io/guide/creating-libraries#publishing-your-library) for. 

Just like `ngx-file-drop` is not built using Ivy, this library project should not either. Publishing a library built with `"angularCompilerOptions": { "enableIvy": true }` is not recommended and can/will lead to compatibility issues by the consumers of it. 

It appears that this is squarely an Angular issue. Creating an Angular Library that uses another Angular library as a dependency is broken.

**Comment by georgipeltekov** [comment]
@justinwilaby 
yes and the workaround ( at least until it is solved on Angular side) is to enable Ivy. If you are about to publish your library ( for instance in npm) there are ways to bypass the checks

**Comment by justinwilaby** [comment]
@georgipeltekov - I tried enabling Ivy locally which built successfully. Using `npm link` to consume the resulting bundle in the parent app again produced errors during the build. In your experience, do symlinks cause unexpected problems with `ngcc`?

**Comment by georgipeltekov** [comment]
Same errors or something new? I didnt use npm link lately, but share some info and I will try to take a look tomorrow ( I am off for today) .
How is the parent app build? With or without ivy?

**Comment by ozkoidi** [comment]
My understanding from [issue 38893](https://github.com/angular/angular/issues/38893) in Angular is that this library was built with Ivy (and that is not supported). See latest comment by [@petebacondarwin](https://github.com/petebacondarwin) 

> the library that you are depending upon has been published (invalidly) after being compiled via Ivy. This is not supported. The ngx-file-drop library must be built in ViewEngine compiler mode before being published. Then you can also build your library in ViewEngine mode.The problem is therefore with the author of the ngx-file-drop library who should not have published a library built with Ivy.

So, is there going to be a fix for this soon? I get the following error: 
`ERROR in Unexpected value 'NgxFileDropModule in .../node_modules/ngx-file-drop/ngx-file-drop/ngx-file-drop.module.d.ts' imported by the module ExampleModule in 'example.module.ts'. Please add a @NgModule annotation.`

**Comment by georgipeltekov** [comment]
@ozkoidi @justinwilaby 
the new version (10.1.1) is build with ViewEngine
