### ISSUE TITLE
ngx-file-drop few of the features(accept, multiple & ng-template) not working as stated

### ISSUE THREAD

**Issue by vamsibassetty08** [georgipeltekov/ngx-file-drop#185]
I've referred to Issue #157 before writing this query and it states multiple and accept works on the input field but it isn't working hence developer has to handle it in dropped event.

As per the [stackblitz](https://stackblitz.com/edit/file-drop-4ju2pa), multiple and accept inputs are not working. I've tried moving the span which has custom content to ng-template but it doesn't see to work. By the way I'm building this sample on Angular 7 in conjunction with ngx-file-drop@5.1.0.
`<file-drop browseBtnLabel="Browse" [showBrowseBtn]="true" (onFileDrop)="dropped($event)" (onFileOver)="fileOver($event)"
  (onFileLeave)="fileLeave($event)" accept="text/*" multiple="false" dropZoneClassName="test" 
  showBrowseBtn="true" browseBtnLabel="Browse" (click)="test()" browseBtnClassName='btn btn-link'>
  <span>Drop files here or </span>
  <ng-template ngx-file-drop-content-tmp let-openFileSelector="openFileSelector">
    drag and drop files here or 
    <button type="button" (click)="openFileSelector()">Browse Files</button>
  </ng-template>
</file-drop>`

Issues:
1) Multiple and accept inputs are not working as stated in the read me file. **accept** is just setting the File type in the choose file dialog. 

2) ng-template doesn't work properly Hence I've to go with direct span

3) test() click event is triggered twice

4) Can developer customize the logic for openFileSelector?

There is very limited information & implementations on the file-drop available for older version Hence could you please update the read me files for older versions with right examples? It surely encourages more audience to use this library.

**Comment by georgipeltekov** [comment]
Hi,

you can check this stackblitz for the ng-template. 
https://stackblitz.com/edit/angular-kpnnez

For the first point - the multiple attribute is add on a later version ,but as stated, they (multiple and accept) wrapped the default html 5 attributes, so this is by design. 
I do not get what do you mean by customize the logic for the openFileSelector. If you want the window to look differently - this is not possible, as this is connected with the way, how the running operation system implements this logic. 

If you must use angular 7 at least try the 6.0.1 version of ngx-file-drop

**Comment by codegastudio** [comment]
Hello

Sorry but i have issue with many of features.
I am using your package in a project under Angular 11.
`accept`, `directory` and `multiple` not working at all.


```
<ngx-file-drop accept="video/*"
               dropZoneLabel="Drop files here"
               dropZoneClassName="drop-zone"
               contentClassName="drop-zone-content"
               [directory]=false
               [multiple]=false
               (onFileDrop)="dropped($event)">
</ngx-file-drop>
```

```
import {Component, OnInit} from '@angular/core';
import { NgxFileDropEntry, FileSystemFileEntry, FileSystemDirectoryEntry } from 'ngx-file-drop';

@Component({
  selector: 'app-video-selector',
  templateUrl: './video-selector.component.html',
  styleUrls: ['./video-selector.component.scss']
})
export class VideoSelectorComponent implements OnInit {

  public files: NgxFileDropEntry[] = [];

  constructor() { }

  ngOnInit(): void {
  }

  public dropped(files: NgxFileDropEntry[]): void {
    this.files = files;
    for (const droppedFile of files) {
      // Is it a file?
      if (droppedFile.fileEntry.isFile) {
        const fileEntry = droppedFile.fileEntry as FileSystemFileEntry;
        fileEntry.file((file: File) => {
          // Here you can access the real file
          console.log(droppedFile.relativePath, file);
        });
      } else {
        // It was a directory (empty directories are added, otherwise only files)
        const fileEntry = droppedFile.fileEntry as FileSystemDirectoryEntry;
        console.log(droppedFile.relativePath, fileEntry);
      }
    }
  }
}

```

When i try to drop a directory,  all files under are listed -> i should not be able to drop a directory
When i try to drop multiple files, all files are listed -> i should not be able to drop multiple files
When i try to drop file which is not a video, file is listed -> i should not be able to drop a file with is not in accept criteria

Regards

**Comment by georgipeltekov** [comment]
@codegastudio  see #157  These attributes are working only for the input field, the rest you can easily determine and ignore
