### ISSUE TITLE
ngx-file-drop max size Limit

### ISSUE THREAD

**Issue by nefissa** [georgipeltekov/ngx-file-drop#187]
Hello,

i want to know what is the max size Limit for the component ngx-file-drop 

Best regards

**Comment by georgipeltekov** [comment]
there is no limit set explicitly.

**Comment by JVPhase** [comment]
So how to pass file size?

**Comment by georgipeltekov** [comment]
@JVPhase  to pass it where? Or to take the file size from the dropped file?

**Comment by JVPhase** [comment]
@georgipeltekov sorry. Yes to take the file size.

**Comment by georgipeltekov** [comment]
@JVPhase  just check the demo in the read.me. after the file is received the data is printed through console.log, so you can see the file structure and all the needed parameters

**Comment by JVPhase** [comment]
@georgipeltekov thanks! Didn't notice

**Comment by myndsol-shivam12833** [comment]
How can we set file upload limit, As an I wanna upload file of 1 mb only, Is there any option for that?

**Comment by myndsol-shivam12833** [comment]
How can I get the file size if there is no option to add fileSizeLimit
