### ISSUE TITLE
Change detection bad issue

### ISSUE THREAD

**Issue by lucian-baciu** [georgipeltekov/ngx-file-drop#189]
I put the <ngx-file-drop> component inside a html file.

After uploading a file, the change detection goes crazy (infinite loop).

Just put this in the html file, with a console.log inside. The log will be full very fast and it doesn't stop

{{printSomeValueChangeDetection()}}

I tried with all properties set, and none of them set. It's happening the same in all cases. The html is isolated, on other pages it is not problem with the change detection.

I also tried with Strategy.ON_PUSH but no effect

I am using angular 8.2.7, and "ngx-file-drop": "^8.0.8"

**Comment by georgipeltekov** [comment]
can you please share a stackblitz example?

**Comment by lucian-baciu** [comment]
Sure:
https://stackblitz.com/edit/angular-8d6efb?embed=1&file=src/app/app.component.ts

**Comment by ahimik** [comment]
Same here. Got infinite change detection loop when dragging over the drop zone and sometimes it gets stucked after the files are dropped.

**Comment by ahimik** [comment]
I didn't dive too much into detail but after a quick research I found out that the root cause of this problem is listening for `dragover` event which gets executed every few hundred milliseconds.
So I had to implement my own dragAndDrop directive and get rid of that event. 
Now everything works fine.
P.S. As an alternative you can try to debounce or handle that event outside angular ng zone but I didn't try.

**Comment by EliCDavis** [comment]
Hey @ahimik do you have a sample of your drag an drop?

It seems like this is 100% breaking change detection in my application, whenever I have a long-standing HTTP request in my `onFileDrop` callback

**Comment by ahimik** [comment]
> Hey @ahimik do you have a sample of your drag an drop?
> 
Yes, sure. I can share my d&d directive but I am not sure where to post it.

**Comment by vanstinator** [comment]
@ahimik I'd love to see this as well. Running into this same issue right now.

**Comment by ahimik** [comment]
Do you prefer a simple library like this(this might take some time) or just code examples?

**Comment by vanstinator** [comment]
Code samples would be great! Thank you!

**Comment by ahimik** [comment]
Sorry for the delay, damn covid.
It's a bit hard to post the complete code since it's spreaded across the app but here are the main fragments:
First of all here is the directive which listens for drag and drop events and fires drop start and drop end events(I planned to extend functionality and track reading file system progress for example):
```

 export abstract class FileDropEvent {
 }

 export class FileDropStartEvent extends FileDropEvent {
 }

 export class FileDropEndEvent extends FileDropEvent {

    constructor(public readonly entries: FileSystemEntry[],
                public readonly error?: Error) {

        super();
    }
 }

 @Directive({
    selector: '[appFileDrop]',
 })
 export class DropFileDirective implements OnInit, OnDestroy {

    @Input() fileDropDisabled = false;

    @Output() fileOver: EventEmitter<boolean> = new EventEmitter();

    @Output() fileDrop = new EventEmitter<FileDropEvent>();

    private processFilesRequest = new Subject<FileList | DataTransferItemList>();

    private processFilesSubscription: Subscription;

    constructor(private ngZone: NgZone,
                private fileService: FileService) {
    }

    @HostListener('dragenter', ['$event'])
    onDragEnter(event: DragEvent) {
        this.preventAndStop(event);
        this.fileOver.emit(true);
    }

    @HostListener('dragleave', ['$event'])
    onDragLeave(event: DragEvent) {
        this.preventAndStop(event);
        this.fileOver.emit(false);
    }

    @HostListener('drop', ['$event'])
    onDrop(event: DragEvent) {
        this.preventAndStop(event);
        this.fileOver.emit(false);
        if (this.fileDropDisabled) {
            return;
        }
        this.processFilesRequest.next(event.dataTransfer.items || event.dataTransfer.files);
    }

    ngOnInit(): void {
        this.processFilesSubscription = this.processFilesRequest.pipe(
            exhaustMap(items => {
                this.fileDrop.next(new FileDropStartEvent());
                return this.fileService.readFileTree(items);
            })
        ).subscribe(fileEntries => this.emitResult(new FileDropEndEvent(fileEntries))
            , error => this.emitResult(new FileDropEndEvent([], error))
        );
    }

    ngOnDestroy(): void {
        this.processFilesRequest.complete();
        if (this.processFilesSubscription) {
            this.processFilesSubscription.unsubscribe();
        }
    }

    private preventAndStop(event: DragEvent): void {
        event.preventDefault();
        event.stopPropagation();
    }

    private emitResult(event: FileDropEndEvent): void {
        this.ngZone.run(() => this.fileDrop.emit(event));
    }
 }
```

and here is the FileService which does the main work of reading file system tree:

```
@Injectable({providedIn: 'root'})
export class FileService {

    private readonly readFileTreeConcurrencyLevel = 2;

    constructor(private fileFactory: FileFactory) {
    }

    /** Reads the whole file tree starting from the given list of directories */
    readFileTree(entries: FileList | DataTransferItemList | FileSystemEntry[]): Observable<FileSystemEntry[]> {

        const entries$: Observable<File | FileSystemEntry> = this.getEntriesAsStream(entries);

        return entries$.pipe(
            mergeMap(item => this.processItem(item), this.readFileTreeConcurrencyLevel),
            toArray(),
            map(items => R.chain(entry => entry, items))
        );
    }

    /** Processing file item */
    private processItem(item: File | FileSystemEntry): Observable<FileSystemEntry[]> {
        if (isFileSystemEntry(item)) {
            return this.processFileSystemEntry(item);
        } else if (item instanceof File) {
            return of([this.fileFactory.createFileEntryFromFile(item)]);
        }
        return of([]);
    }

    /**
     * Processing the concrete FileSystemFileEntry.
     * Reads all children if it's a directory otherwise returns as it is;
     */
    private processFileSystemEntry(entry: FileSystemEntry): Observable<FileSystemEntry[]> {
        if (isFileEntry(entry)) {
            return of([entry]);
        } else if (isDirectoryEntry(entry)) {
            return this.readDirectoryEntries(entry).pipe(
                concatMap(entries => this.readFileTree(entries)),
                map(entries => entries.concat(entry)) // Добавляем саму директорию в список
            );
        }
        return of([]);
    }

    /** Reads all directory entries using Webkit FileSystemDirectoryReader in batches */
    private readDirectoryEntries(entry: FileSystemDirectoryEntry): Observable<FileSystemEntry[]> {
        const reader = entry.createReader();
        return this.getNextBatch(reader).pipe(
            expand(entries => entries.length > 0 ? this.getNextBatch(reader) : EMPTY),
            toArray(),
            map(items => R.chain(item => item, items))
        );
    }

    /** Getting next batch of FileSystemEntries until empty */
    private getNextBatch(reader: FileSystemDirectoryReader): Observable<FileSystemEntry[]> {
        return new Observable<FileSystemEntry[]>(observer => {
            reader.readEntries((entries: FileSystemEntry[]) => {
                    observer.next(entries);
                    observer.complete();
                },
                error => observer.error(error));
        });
    }

    private getEntriesAsStream(entries: FileList | DataTransferItemList | FileSystemEntry[]): Observable<File | FileSystemEntry> {

        if (Array.isArray(entries)) {
            return from(entries);
        } else if (entries instanceof FileList) {
            return from(Array.from(entries));
        } else if (entries instanceof DataTransferItemList) {
            return from(this.convertDataTransferItemsToFileEntries(entries));
        }
    }

    private convertDataTransferItemsToFileEntries(itemList: DataTransferItemList): FileSystemEntry[] {
        const items = [];
        // tslint:disable-next-line:prefer-for-of
        for (let i = 0; i < itemList.length; i++) {
            items.push(itemList[i].webkitGetAsEntry());
        }
        return items;
    }


}

```

The interfaces for FileSystemEntry are quite similar as well as the final implementation of the drag and drop component. Let me know if you need that as well

**Comment by georgipeltekov** [comment]
If the dragover vs dragenter is the problem vs solution, I can easily change the event to dragenter, however I am afraid of a backward compatibility and whether this wont brake already working solutions. Another option will be to add addition property, that once set to true to prefer dragenter over dragover.....

**Comment by ahimik** [comment]
> If the dragover vs dragenter is the problem vs solution, I can easily change the event to dragenter, however I am afraid of a backward compatibility and whether this wont brake already working solutions. Another option will be to add addition property, that once set to true to prefer dragenter over dragover.....

That would be nice and yes, in my case changing dragover to dragenter solved the problem.
Dragenter occurs only once when you actually enter drag zone but dragover according to the spec https://developer.mozilla.org/en-US/docs/Web/API/Document/dragover_event occurs every hundred milliseconds and somehow causes angular's change detection to run in infinite loop.

BTW: I don't see any backward compatibility problem changing from DragOver to dragEnter since it is the implemetation details which are not the part of public API.

**Comment by georgipeltekov** [comment]
can you check version 9.0.1 , that I just released.

P.S. pull requests and contribution are always more than welcome

**Comment by georgipeltekov** [comment]
let me know if the problem still persist in the latest versions

**Comment by SenneWouters** [comment]
I had the same issue (change detection going crazy). I use OnPush changedetection with @inputs and @outputs to work around it.
