### ISSUE TITLE
accept parameter works in 8.0.3 but not in 8.0.8

### ISSUE THREAD

**Issue by jeffunderdown** [georgipeltekov/ngx-file-drop#190]
The "accept" input binding correctly filters file types in the file dialog on 8.0.3 but in version 8.0.8 all file types are filtered from the file dialog even when the property is not bound and the default is applied.

**Comment by georgipeltekov** [comment]
Hmm, 

that's look strange. Could you please share a stackblitz example,  I just tested it: https://stackblitz.com/edit/angular-5uqa2d

and it seems to work fine.

**Comment by georgipeltekov** [comment]
I am closing this one. If you still face any problems, please feel free to re-open it.
