### ISSUE TITLE
[BUG] dataTransfer.dropEffect doesn't seem to work

### ISSUE THREAD

**Issue by max-gtz** [georgipeltekov/ngx-file-drop#191]
Since Chrome 76, it should be possible to drag & drop emails directly from Outlook to the browser for uploading .msg files. 

In the default case, Outlook will delete emails from your inbox after you dragged them to Chrome because the standard dataTransfer.dropEffect for the DragEvent is "move". 
That dropEffect value needs to be set to "copy" to allow dragging Outlook emails into Chrome without deleting them.

I can see that you're trying to do that here [ngx-file-drop.component.ts#L136](https://github.com/georgipeltekov/ngx-file-drop/blob/11a31de6f7cbd29fd34e3430a9fbed52bdffac2b/src/ngx-file-drop/ngx-file-drop.component.ts#L136). But somehow it doesn't seem to work, Chrome still handles that drag & drop action as "move". 

It is indeed possible with multiple other libraries (e.g. Uppy.JS). So there must be a solution, but I didn't find it yet.

**Comment by zaki785** [comment]
@georgipeltekov

I have the same issue on my side. By dragging an email from Outlook application to my website, it moves the mail to the trash folder after dragged it.

It seems to be an issue on the 'event.dataTransfer.effectAllowed' property which is not set to the 'copy' value.

It is used on production environment and didn't find a way to solve this issue.

Could we please have a look on this subject ? Many many thanks in advance

**Comment by CesarD** [comment]
I'm getting the same behavior. Emails coming from Outlook are being dumped into Deleted Items.
Is there any chance for this to be reviewed and fixed?

**Comment by CesarD** [comment]
[BUMP]

Any idea as to how this could be fixed?

**Comment by almai** [comment]
Same problem here. Is there a chance to get a small hint from @georgipeltekov? Would be very appreciated. Thanks in advance!

**Comment by CesarD** [comment]
I found a way to fix it and I just created the PR. Hope this helps and author can merge it as soon as he can possibly have some time for it 😃

**Comment by georgipeltekov** [comment]
fixed in 11.0.1, thanks to @CesarD
