### ISSUE TITLE
[BUG] router.navigate fails when dropping files

### ISSUE THREAD

**Issue by cre8** [georgipeltekov/ngx-file-drop#192]
I analyse a file and want to navigate to another component. Selecting a file will fire the ngOnInit method in the next component. But when i drop the file, the url changes and the constructor of the next component is called, but not the ngOnInit method.

**Comment by georgipeltekov** [comment]
the dropping should not impact the url... could you please share a stackblitz example

**Comment by cre8** [comment]
@georgipeltekov here you go: https://stackblitz.com/edit/angular-7zs8jr

Browsing the file will fire the alert in the ngOnInit function, but darg and drop does not.

**Comment by georgipeltekov** [comment]
Hmmm interesting. I think this is connected with how the browser implement differently the both actions - selection file and dropping an element. Did you check these two links:
https://stackoverflow.com/questions/35110690/ngoninit-not-being-called-when-injectable-class-is-instantiated

https://stackoverflow.com/questions/39962857/ngoninit-not-called-when-same-component-is-loaded-with-different-data/39962929

**Comment by cre8** [comment]
Found a solution, had to call 
`this.ngZone.run(() => this.router.navigate(['/success'])).then();`

instead of just 

`this.router.navigate(['/success']);`

Since other people had the same error with different situations (https://stackoverflow.com/questions/53133544/angular-7-routerlink-directive-warning-navigation-triggered-outside-angular-zon/53213909) it's not a bug of this library.
