### ISSUE TITLE
 Programatically clear file input element

### ISSUE THREAD

**Issue by boorac** [georgipeltekov/ngx-file-drop#193]
I would like to have a button that clears all dropped files, so I can offer the user a clear UI if he wishes to upload new files. Is there a way of achieving that?

**Comment by georgipeltekov** [comment]
You can simply add this button and make them clear the structure, that holds your files. Would this not work? 

For instance, if we look at the read.me example, that would be the "files"

Did you try something?

**Comment by boorac** [comment]
Yes, at this point in time I am just reloading the page (I wanted to be sure that I have a clean state). Obviously this is a hack and I would like to do it clean.
```
public clearFiles() {
    this.router.routeReuseStrategy.shouldReuseRoute = () => false;
    this.router.onSameUrlNavigation = 'reload';
    this.router.navigate([this.router.url]);
  }
```
So setting:
`this.files = [];` 
should suffice?

**Comment by georgipeltekov** [comment]
Yes this should do the work. If you like, please share a stackblitz example and I will check it
