### ISSUE TITLE
Progress bar or spinner

### ISSUE THREAD

**Issue by fridagit** [georgipeltekov/ngx-file-drop#198]
Is it possible to use a spinner while uploading images or a progress bar?

**Comment by georgipeltekov** [comment]
It is not in the library, but if you start displaying the spinner at the beginning of the drop and stop it, once all the files ( in the callback) are proceed , that should do the work

**Comment by fridagit** [comment]
In the dropped function it is to late to show the spinner. I quess it is here I should hide it again but there is no method at the beginning of the drop right? Or do you mean the fileOver function?

**Comment by georgipeltekov** [comment]
I am closing this, as it is up to the developer to customize the desired spinner/ progress bars
