### ISSUE TITLE
Adding Add button

### ISSUE THREAD

**Issue by beeing** [georgipeltekov/ngx-file-drop#2]
Hi, great work on this component.

A suggestion for you to add in the Add Files button.
Not all users may want to drag though.

**Comment by georgipeltekov** [comment]
Hey,

thank you for your feedback and for using the component. In general the idea of the component is to provide specific features, dragging and dropping of files/folders and it usage to be as simple as possible. If I am about to add this button it will bring additional complications, for instance, where the button should be (top,right, bottom ect.) Should it be with custom design, should it be for files or folders. Of course I can always add custom parameters to handle all this, but I think this will be too much and will make the usage not so straightforward. 
Also it is very easy to add this functionality in the way you want it and customize it, how you want to be.
For instance, if you like to hide the default button and to have custom upload button, this should do the work:

` 
<input type="file" id="selectedFile" (change)="onChange($event)" multiple style="display: none;" />
<input type="button"  class="btn btn-primary btn-xs" value="Custom Btn " onclick="document.getElementById('selectedFile').click();" /> 
`

**Comment by beeing** [comment]
Thanks for the feedback, appreciated.

**Comment by rankill** [comment]
Hello, question, how can I handle the files the same way that UploadEvent does? the parameter $event is not the same as we drop a file. Thanks!!

**Comment by georgipeltekov** [comment]
by using the library. and I am not quite sure I understand your questions, but for sure, this is not the right place to ask, as this issue is for complete different topic

**Comment by Nxt3** [comment]
@georgipeltekov What @rankill is asking is that if we handle the input ourselves with a button, then the event fired isn't the same as your `UploadEvent`. This means if I drop a file on my selector, the triggered event will be different than that of using an `<input>` field and looking at the `files` property.

He's asking how would we get both of those into the same type.

**Comment by georgipeltekov** [comment]
Unfortunately this is not possible. The UploadEvent is coming from the library and there is a lot of custom logic behind it, while the event from the input is coming from the html5 and this is a strict browser behavior.

**Comment by Nxt3** [comment]
Could you maybe offer the ability to choose which event to emit? Having a "Browse" button is pretty normal for good UX and not being able to handle the different events is going to prove problematic.

Maybe just the ability to make the drag and drop area clickable and have it think files were dropped on?

**Comment by georgipeltekov** [comment]
@Nxt3  check version 5.0.2. I add a new property, so you can decide, whether browse file button to be shown or not

**Comment by Nxt3** [comment]
@georgipeltekov This is perfect. I was able to use my own button and everything with this addition. Thanks so much!
