### ISSUE TITLE
Invalid path when selecting directories via button

### ISSUE THREAD

**Issue by btxtiger** [georgipeltekov/ngx-file-drop#201]
When selecting directorys, the attribute `relativePath` of `droppedFile: NgxFileDropEntry` is not correct. Instead I have to check `droppedFile.fileEntry.file(f => d. webkitRelativePath)` to check, if the file comes from a folder selection.
![image](https://user-images.githubusercontent.com/15804690/81308259-dcee3100-9081-11ea-87d2-7c1d9d08acba.png)
![image](https://user-images.githubusercontent.com/15804690/81308300-e7a8c600-9081-11ea-8351-2903524f8963.png)

**Comment by georgipeltekov** [comment]
Yes, you have to call the callback to receive this information, as described in the read.me example.
