### ISSUE TITLE
Unable to reimport previous imported file

### ISSUE THREAD

**Issue by ahmedeldeeb25** [georgipeltekov/ngx-file-drop#202]
I think ngx-file-drop cache or store the previous imported files, I need to disable that as I can't reimport the file again.
one of my reason for that, I updated a specific file on my PC and need to reimport again to override the old version of it.

**Comment by georgipeltekov** [comment]
how do you store the files? I assume once you receive the files from the library you are storing them in some local structure ( list for instance) and after that you are not clearing it.

Could you share stackblitz example?
