### ISSUE TITLE
Angular 10 support missing

### ISSUE THREAD

**Issue by Kungitoo** [georgipeltekov/ngx-file-drop#204]
Hey,
I just tried upgrading my project to ng10 and this is the last missing link. Do you plan on supporting the latest angular versions generally?

**Comment by andreacirri** [comment]
Hi,

when the lib will be updated to Angular 10?

**Comment by CodeWorldIndustries** [comment]
I'm using Angular 10.0.0 and its working fine...

**Comment by Swordfish815** [comment]
Hello,

I also encounter an issue after migrating to angular 10: if I ng serve the application, the application is not working, I have an error on "Uncaught TypeError: Cannot read property 'id' of undefined" on registerNgModuleType.

if I do ng build --prod, I obtain more detail:
```
ERROR in node_modules/ngx-file-drop/ngx-file-drop/ngx-file-drop-entry.d.ts:7:22 - error NG6002: Appears in the NgModule.imports of SharedModule, but could not be resolved to an NgModule class.

This likely means that the library (ngx-file-drop) which declares NgxFileDropEntry has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

7 export declare class NgxFileDropEntry {
                       ~~~~~~~~~~~~~~~~
node_modules/ngx-file-drop/ngx-file-drop/ngx-file-drop-entry.d.ts:7:22 - error NG6003: Appears in the NgModule.exports of SharedModule, but could not be resolved to an NgModule, Component, Directive, or Pipe class.

This likely means that the library (ngx-file-drop) which declares NgxFileDropEntry has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

7 export declare class NgxFileDropEntry {
                       ~~~~~~~~~~~~~~~~
src/app/shared/shared.module.ts:32:14 - error NG6002: Appears in the NgModule.imports of AppModule, but itself has errors
```

If I comment the code related to ngx-file-drop, the application works.

Do you know if there is a way to fix this?

**Comment by Swordfish815** [comment]
> @Kungitoo & @andreacirri I'm using Angular 10.0.0 and its working fine...

@CodeWorldIndustries, I notice that enableIvy is false in tsconfig.json that might explain why it's not working with angular 10 ?
`  "angularCompilerOptions": {
    "enableIvy": false`

**Comment by Swordfish815** [comment]
I've to correct myself: ngx-file-drop is working with angular 10.
I made an error with the import, all is working as intended now.

**Comment by snike1985** [comment]
@georgipeltekov What about supporting ivy? Will it support ivy in close time?
