### ISSUE TITLE
Call File_Upload Api only once for multiple file

### ISSUE THREAD

**Issue by shridharSynerzip** [georgipeltekov/ngx-file-drop#205]
`

      public files: NgxFileDropEntry[] = [];
 
  
      public dropped(files: NgxFileDropEntry[]) {
    
      this.files = files;
    
      for (const droppedFile of files) {
 
      // Is it a file?
      if (droppedFile.fileEntry.isFile) {
        const fileEntry = droppedFile.fileEntry as FileSystemFileEntry;
        fileEntry.file((file: File) => {
 
          // Here you can access the real file
          console.log(droppedFile.relativePath, file);
 
          /**
          // You could upload it like this:
          const formData = new FormData()
          formData.append('logo', file, relativePath)
 
          // Headers
          const headers = new HttpHeaders({
            'security-token': 'mytoken'
          }) 
        
      } else {
        // It was a directory (empty directories are added, otherwise only files)
        const fileEntry = droppedFile.fileEntry as FileSystemDirectoryEntry;
        console.log(droppedFile.relativePath, fileEntry);
      }
    }
  this.http.post('https://mybackend.com/api/upload/sanitize-and-save-logo', formData, { headers: headers, responseType: 'blob' })
          .subscribe(data => {
            // Sanitized logo returned from backend
          })
          **/
 
        });`

I am using above code to upload multiple files on Drag-drop files, but my api is called before for loop on "files" completes its execution.
I want to call call api only once after the formData appended for all files.
But it seems that "fileEntry.file" calls asynchronously.

**Comment by georgipeltekov** [comment]
Yes, the call is asynchronous, as per  HTML 5 File Api documentation.  You can call your functions, once all the file calls are ready.

**Comment by shridharSynerzip** [comment]
Can you please help me for , how should I know the all file calls are ready in same event?

**Comment by georgipeltekov** [comment]
for instance you can have counter and increment it once every call is completed. On some time interval check if the counter is equal the size of the received file list. For sure there are other options as well.

**Comment by shridharSynerzip** [comment]
ok, thank you very much.
