### ISSUE TITLE
dropZoneClassName is applied but the styles won't reflect

### ISSUE THREAD

**Issue by lmanapure** [georgipeltekov/ngx-file-drop#207]
I have added the component in my app component like this:
`<ngx-file-drop
  dropZoneLabel="Drop files here"
  [dropZoneClassName]="'drop-zone'"
  (onFileDrop)="dropped($event)"
  (onFileOver)="fileOver($event)"
  (onFileLeave)="fileLeave($event)"
>`

My stylesheet is:
`.drop-zone {

  height: 177px;
  margin: auto;
  border: 2px dashed #b6b6c9;
  border-radius: 10px;
  background-image: url('/assets/images/cloud-2044823_960_720.png');
  background-repeat: no-repeat;
  background-size: 100px;
  background-position-x: center;
  background-position-y: top;

  .ngx-file-drop__content {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: flex-end;
    height: 100%;

    .browsePortion {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
    }
  }
}`

In the generated html, I can see the following:
`<ngx-file-drop _ngcontent-boy-c307="" dropzonelabel="Drop files here" _nghost-boy-c305="" ng-reflect-drop-zone-label="Drop files here" ng-reflect-drop-zone-class-name="drop-zone"><div _ngcontent-boy-c305="" class="drop-zone"><div _ngcontent-boy-c305="" class="ngx-file-drop__content"><input _ngcontent-boy-c305="" type="file" class="ngx-file-drop__file-input" accept="*" multiple=""><button _ngcontent-boy-c307="" type="button" class="ng-star-inserted">Browse Files</button></div></div></ngx-file-drop>`

but the styles do not reflect correctly.

Can it be because the following attribute is missing from the component:
`encapsulation: ViewEncapsulation.None`

**Comment by georgipeltekov** [comment]
see #21

**Comment by lmanapure** [comment]
So, I think the issue is I am specifying the custom style in my component's stylesheet. Ideally it should work that way. I will try by setting view encapsulation in the code to see if that works.
