### ISSUE TITLE
File dropped and file browsed are different.

### ISSUE THREAD

**Issue by popoleeMaster** [georgipeltekov/ngx-file-drop#210]
I am using the latest version.

when we use the browse button and select a file, the object looks like 
![2020-08-05_15-52](https://user-images.githubusercontent.com/46583218/89381266-d54b3080-d733-11ea-8818-64d5715ef0bb.png)

We use the file Promise to get the file and it's ok.

When I drag it looks like this :
![2020-08-05_15-53](https://user-images.githubusercontent.com/46583218/89381267-d714f400-d733-11ea-80fb-d567cea0e405.png)

And to get the File, I guess we need to use the 

`fileEntry.filesystem.file`

but the type of `NgxFileDropEntry`

is 

```
export declare class NgxFileDropEntry {
    relativePath: string;
    fileEntry: FileSystemEntry;
    constructor(relativePath: string, fileEntry: FileSystemEntry);
}
```

with fileEntry beeing 

```
export interface FileSystemEntry {
    name: string;
    isDirectory: boolean;
    isFile: boolean;
}
```

so I don't get how we are supposed to get the file of a dropped file correctly, cause there is no interface matching this type.

Is it me that is using it wrong ?

thanks.

**Comment by georgipeltekov** [comment]
In the read.me file there is an example with dropped file , in the Usage section. I think this is what you are looking for.

**Comment by popoleeMaster** [comment]
hi, thanks for the reply, I was using the readme, but I made the issue to quickly, and I found out my missmatch with type. 

Sorry for troubles.
