### ISSUE TITLE
using button with openFileSelector and directory=false only shows/selects folders but no files

### ISSUE THREAD

**Issue by clehmeier** [georgipeltekov/ngx-file-drop#211]
Hello Georg,

thanks for your great work!
If using drag&drop to upload files, everything is working. 

I have a small issue with the button-option:
Now I startet to add the "Browse file"-Button as in your example:

`<ngx-file-drop
...
<ng-template ngx-file-drop-content-tmp let-openFileSelector="openFileSelector">
          Optional custom content that replaces the the entire default content.
          <button type="button" (click)="openFileSelector()">Browse Files</button>
</ng-template>
</ngx-file-drop>
...`

But if button is clicked, it shows up a directory selection window, not a file selection window. I can just select a full folder and uploading all containing files, but I would expect a selection for single file (cause I am unsing the multiple=false option...)

![wrong_windowtype](https://user-images.githubusercontent.com/70153794/91063361-2e6cfc80-e62e-11ea-87ae-90a3f467169a.png)

What am I doing wrong?

Using 
ngx-file-drop v9.0.1
Angular 8.2

Thank you very much, 
  Christian

**Comment by clehmeier** [comment]
Here is translation for the screenshot:

"Ordner zum Hochladen auswählen" => "choose folder to upload"
"Odner" => "folder"

**Comment by georgipeltekov** [comment]
Hi,

could you please share  a stackblitz example, or at least everything between <ngx-file-drop> and </ngx-file-drop>

**Comment by clehmeier** [comment]
Thanks for your fast reply,

while preparating code for stackblitz I have found the cause: 
using option "directory" causes buttonclick to show always directory-open-window. Setting it to true or false is irrelevant.

        <ngx-file-drop [id]="12345" [dropZoneLabel]="Drop Files here" [accept]="*.pdf"
        multiple="false" **directory="true"** (onFileDrop)="filedropped($event)">
          <ng-template ngx-file-drop-content-tmp let-openFileSelector="openFileSelector">
            Optional custom content that replaces the the entire default content.
            <button type="button" (click)="openFileSelector()">Browse Files</button>
          </ng-template>
        </ngx-file-drop>


So I don't know if this is expected behaviour or not - my problem is solved.

Thanks!
  Christian

**Comment by clehmeier** [comment]
used wysiwyg-editor to make bold, but now it shows up with **: **directory="true"**.
In my code directory="true" is of course without the **...
