### ISSUE TITLE
Setting dropZoneClassName/contentClassName seems not working

### ISSUE THREAD

**Issue by DemianSteelstone** [georgipeltekov/ngx-file-drop#215]
Hi! I'm trying to apply my own style but it doesn't seem to work
I created an example, am I missing something?
https://stackblitz.com/edit/angular-ivy-u1n5fk

**Comment by georgipeltekov** [comment]
The provided example doesn`t seems to work, however you can check #21

**Comment by DemianSteelstone** [comment]
Fixed example

I've set
dropZoneClassName="my-class"
contentClassName="some-class"

```
.my-class {
    height: 100px;
    margin: auto;
    border: 4px dotted red !important;
    border-radius: 30px;
  }
.some-class {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100px;
    color: green;
}
```
In result, I got this
<img width="436" alt="Снимок экрана 2020-10-15 в 13 56 06" src="https://user-images.githubusercontent.com/5743752/96114447-4bb39e00-0eee-11eb-8b29-2c38da941391.png">

**Comment by georgipeltekov** [comment]
did you check the comments here #21 ?  You need to define your styles in styles.css
