### ISSUE TITLE
Version 10.0.0 seems incompatible with storybook

### ISSUE THREAD

**Issue by kossmoboleat** [georgipeltekov/ngx-file-drop#216]
After upgrading to 10.0.0 I cannot use ngx-file-drop in our storybook anymore. I'm not sure if it's a storybook or ngx-file-drop issue.

The file drop isn't displayed and the browser console has an error message:
`Unhandled Promise rejection: Failed to load ngx-file-drop.component.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load ngx-file-drop.component.html undefined`

![Screen Shot 2020-10-21 at 17 00 42](https://user-images.githubusercontent.com/1618518/96738474-0cd68a00-13bf-11eb-8819-bd037da01136.png)

Otherwise we're using the latest angular 10.x and latest storybook revisions.

This is the last working configuration before upgrading ngx-file-drop:

```
  "dependencies": {
    "@angular/animations": "^10.1.6",
    "@angular/cdk": "^10.2.5",
    "@angular/common": "^10.1.6",
    "@angular/compiler": "^10.1.6",
    "@angular/core": "^10.1.6",
    "@angular/forms": "^10.1.6",
    "@angular/localize": "^10.1.6",
    "@angular/material": "^10.2.5",
    "@angular/platform-browser": "^10.1.6",
    "@angular/platform-browser-dynamic": "^10.1.6",
    "@angular/router": "^10.1.6",
    "@briebug/cypress-schematic": "^2.0.0",
    "@swimlane/ngx-datatable": "^18.0.0",
    "date-fns": "^2.16.1",
    "ibankit": "^1.3.1",
    "keycloak-angular": "^8.0.1",
    "keycloak-js": "11.0.2",
    "ngx-file-drop": "^10.0.0",
    "rxjs": "^6.6.3",
    "tslib": "^2.0.3",
    "uuid": "^8.3.1",
    "zone.js": "^0.11.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1001.7",
    "@angular/cli": "^10.1.7",
    "@angular/compiler-cli": "^10.1.6",
    "@angular/language-service": "^10.1.6",
    "@aws-cdk/aws-certificatemanager": "1.67.0",
    "@aws-cdk/aws-s3": "1.67.0",
    "@aws-cdk/aws-s3-deployment": "1.67.0",
    "@aws-cdk/core": "1.67.0",
    "@babel/core": "^7.12.3",
    "@cypress/webpack-preprocessor": "4.1.0",
    "@storybook/addon-actions": "^6.0.26",
    "@storybook/angular": "^6.0.26",
    "@storybook/preset-scss": "^1.0.3",
    "@types/jest": "^26.0.15",
    "@types/node": "^14.14.0",
    "aws-cdk": "^1.67.0",
    "babel-loader": "^8.1.0",
    "codelyzer": "^6.0.1",
    "css-loader": "^5.0.0",
    "cypress": "^4.12.1",
    "husky": "^4.3.0",
    "jest": "^26.6.0",
    "jest-environment-jsdom-sixteen": "^1.0.3",
    "jest-preset-angular": "^8.3.1",
    "prettier": "^2.1.2",
    "pretty-quick": "^3.1.0",
    "ts-jest": "^26.4.1",
    "ts-loader": "^8.0.6",
    "ts-node": "^9.0.0",
    "tslint": "^6.1.3",
    "tslint-config-prettier": "^1.18.0",
    "typescript": "~3.9.7",
    "webpack-bundle-analyzer": "^3.9.0"
  }
```

**Comment by georgipeltekov** [comment]
could you please share a stackblitz example?

**Comment by kossmoboleat** [comment]
I'm not sure how to create a stackblitz with storybook, but here's a repo:
https://github.com/kossmoboleat/angular-storybook

It's the current ng's default app with storybook added. It has an AppComponent that works fine in the app but a storybook story with the same component that throws the error in the console and crashes storybook.

**Comment by georgipeltekov** [comment]
You can go to https://stackblitz.com/ and create it , it is pretty straightforward, otherwise, without such example I cannot help you

**Comment by kossmoboleat** [comment]
Yes, creating the stackblitz was not hard:
https://stackblitz.com/edit/github-6mhy7p

The problem is that one cannot tell stackblitz to open the storybook instead of the normal angular app.

Showing this in stackblitz aside could it be that ngx-file-drop 10.0.0 depends on AoT compilation? Seems like they need some extra configuration to enable that...

https://github.com/storybookjs/storybook/issues/10760

**Comment by georgipeltekov** [comment]
Yes, maybe this is the problem. Does it work with versions, prior to 10.0.0. It yes - you might to have to use them, instead of the latest one.

**Comment by kossmoboleat** [comment]
Yes, it works with the latest 9.x release. Seems someeone is working storybook AoT support, but it doesn't seem it's coming soon.

Here's a similar issue described in their issues:
https://github.com/storybookjs/storybook/issues/11693

And their work in progress PR for support is this:
https://github.com/storybookjs/storybook/pull/11157

You might want to mark this issue as closed then because it's not an issue with ngx-file-drop, which also works very well with version 9.x, Thanks btw :-). 

It might be worth keeping it open for others looking into this or documenting that one needs ivy compatible tools to use version 10.x. I noticed for example that codesandbox.io (which would have allowed running storybook) doesn't seem to support ivy and it has to be enabled in stackblitz.com too to make it work.
