### ISSUE TITLE
Question: Safari support

### ISSUE THREAD

**Issue by alastair-todd** [georgipeltekov/ngx-file-drop#217]
Wondering what the issue with Safari is?

https://caniuse.com/fileapi

**Comment by tiagomsmagalhaes** [comment]
I tested the demo page on Safari on Big Sur and it's working. @georgipeltekov any issue that you had found in older versions of Safari?

**Comment by georgipeltekov** [comment]
there were some complains in the very first days of the library and compatibility issues , but obviously this is not relevant any more. I will update the readme in the next release
