### ISSUE TITLE
File drop accept doesn't work correctly. 

### ISSUE THREAD

**Issue by galstyanzara** [georgipeltekov/ngx-file-drop#220]
`<ngx-file-drop dropZoneLabel="Drop files here" (onFileDrop)="dropped($event)" (onFileOver)="fileOver($event)"
               accept=".png, .jpg, jpeg" (onFileLeave)="fileLeave($event)">
    <ng-template ngx-file-drop-content-tmp let-openFileSelector="openFileSelector">
        Optional custom content that replaces the the entire default content.
        <button type="button" (click)="openFileSelector()">Browse Files</button>
    </ng-template>
</ngx-file-drop>`

With this, it must accept only ".png, .jpg, jpeg" types, but this works only when you open a file selector by a click on "Browse Files" when you drop some file it accepts any type.

**Comment by georgipeltekov** [comment]
See #157
