### ISSUE TITLE
Package contains root folder instead of dist folder

### ISSUE THREAD

**Issue by maartenmensink** [georgipeltekov/ngx-file-drop#24]
@georgipeltekov I just installed the package 2.0.0 the version.

It seems that the root was packaged and instead of the dist folder. 

the publish command should be `npm publish dist` so that it only packages the dist folder and not the entire root folder of the repository. 

I noticed you reverted a change in the readme.md file 

`import { FileDropModule } from 'ngx-file-drop/src/lib/ngx-drop';`

but it should be 

`import { FileDropModule } from 'ngx-file-drop';`

that doesn't work due incorrect packaging.

**Comment by georgipeltekov** [comment]
fixed in 2.0.1
