### ISSUE TITLE
[BUG] 11.2.0 breaks previous functionality if `accept` has mimetypes instead of extensions

### ISSUE THREAD

**Issue by adhirajsinghchauhan** [georgipeltekov/ngx-file-drop#243]
#242 is a good feature, but it's half-baked and it breaks existing functionality. The file input type allows both [extensions & mimetypes][input-file-type-specifiers], yet that PR assumed `accept` only had extensions.

For example, this no longer works (i.e. if the user drops a valid image file, nothing happens anymore), and there's no feedback of any kind about what went wrong.
```html
<ngx-file-drop accept="image/*" ...></ngx-file-drop>
```

Why was it merged & released without any testing? Version was bumped from 11.1.0 to 11.2.0, and assuming this library follows [SemVer][semver], the minor version was incremented in a non-backwards compatible manner.

A proper solution to implement file validation would need to include logic for both extensions & mimetypes, and an event must be emitted that shows the status of the drop. Ideally, it should be part of `onFileDrop` itself.

[input-file-type-specifiers]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers
[semver]: https://semver.org/

**Comment by HexagonSun** [comment]
Can confirm, this broke things for me, too.

In my case `accept` was bound to `undefined`, which caused an exception.
Workaround seemed to be to set a default value of  `*`, since that immediately bypasses `isAcceptedExtension`.
But for now, I'm rolling back to 11.1.0.

**Comment by tobium** [comment]
additionally have white spaces between multiple accept extensions leads to broken accept check too:

in version 11.1.0 this worked: [accept]="'.png, .jpg, .gif, .jpeg, .pdf'"
in version 11.2.0 the white space after each comma broke the functionality because of the slice(",") call which does not  spaces take into account...

so in 11.2.0 only this works: [accept]="'.png,.jpg,.gif,.jpeg,.pdf'"

**Comment by georgipeltekov** [comment]
it should be ok with 11.3.0
