### ISSUE TITLE
Create ivy build for Angular 13+

### ISSUE THREAD

**Issue by btxtiger** [georgipeltekov/ngx-file-drop#250]
Getting the following message when building the app:
```
⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- ngx-file-drop [es2015/esm2015] (georgipeltekov/ngx-file-drop)
Encourage the library authors to publish an Ivy distribution.
```

**Comment by georgipeltekov** [comment]
couple of months ago it was still **not** recommended to publish ivy libraries in npm, frankly I don't know whether this is changed or not, but as far as I see there are still discussions about this topic

**Comment by json-derulo** [comment]
As far as I know, the ViewEngine has been removed with Angular 13. It is now recommended to use the Partial Ivy format, according to the [docs](https://angular.io/guide/creating-libraries#publishing-libraries).

**Comment by e-oz** [comment]
Could you please reconsider? Angular 14 is almost here.
