### ISSUE TITLE
Navigation not fired after file drop

### ISSUE THREAD

**Issue by cre8** [georgipeltekov/ngx-file-drop#251]
I want to redirect to another site after a file was dropped. The url changed in the navigation bar, but the view is still the same. When I select a file the normal way with my OS, the redirect works fine.

**Comment by Eicoon** [comment]
You have to use `ngZone.run` because the navigation is triggered outside the Angular zone.
E.g. `this.ngZone.run(()=>this.router.navigate(['yourURL]).then());`
Don't forget to import NgZone from '@angular/core'.
