### ISSUE TITLE
Inconsistent behavior when (edit: Dragging folders from networked drives)

### ISSUE THREAD

**Issue by EnigmaticaGH** [georgipeltekov/ngx-file-drop#26]
![Screenshot of issue](https://user-images.githubusercontent.com/11641630/33026784-3708e738-cddf-11e7-8d5e-150612531d52.png)

The above attachment is a result of me dragging the exact same folder several times. The dragged folder is a network drive if that makes a difference.

I also notice that sometimes the uploadFile queue is not fully empty when a new dropped event occurs. This was tested by dragging the same large folder as shown above, then dragging an empty folder afterwards. The empty folder drop event contained many files from the previous event.

Tested on:
Chrome 62
NodeJS 8.6.0
npm 5.3.0
Angular 4 CLI 1.5.2

**Comment by georgipeltekov** [comment]
Hi, maybe it was not the empty folder event, but the previous event, as the reading is done on chunks, but both the huge folder and the empty folder should be there at the end of the day. Can you test with the Demo page and check how much files are read and if the result is the same. If there are a lof of nested files or folders maybe it will take some time to visualize everything

**Comment by EnigmaticaGH** [comment]
It's pretty inconsistent on the demo as well. Sometimes I get 2 pages (14 files), other times I get 4 pages (the full set), but most of the time, I get something in between. I'm fairly sure it might be due to the fact that it's a networked drive and some of the files are compressed at the filesystem level. 

I just tested by first moving the folder from the network drive to my local drive and the transfer worked flawlessly. I'm not sure if you can fix the issue with network drives, but it's not a huge deal at least for my use case, as I can move them to my local drive before moving them to my web-app.
