### ISSUE TITLE
The type of some files are missing in chrome caused by "webkitGetAsEntry()"

### ISSUE THREAD

**Issue by bazsoja** [georgipeltekov/ngx-file-drop#261]
Hello, 

First of all thank you for your work. We are using you component for years now and it works perfectly in 99% of the cases.
We have now a problem Using Chrome file upload because the file type is empty for some file types. (It was reported for the file type ".mov" but it is present for a few more.)

After a loot of search and analyses I found out the the problem is that this component reads the file using webkitGetAsEntry() which does not reads the type of the file in Chrome. In FF it works perfectly.

As you can see there is an old bug report (https://bugs.chromium.org/p/chromium/issues/detail?id=155455) which is still open today.
Since the documentation of "webkitGetAsEntry()" (https://developer.mozilla.org/en-US/docs/Web/API/DataTransferItem/webkitGetAsEntry) states that this is a non standard method would it be a possibility to read the file with "item.getAsFile()" if the webkitGetAsEntry() does not returns the type of the file? 

Thank you!

**Comment by georgipeltekov** [comment]
should be ok with 14.0.1

**Comment by tomriddle1234** [comment]
Maybe still not working in Chromium 107, Firefox is fine, but Chrome sometimes gets empty file entry, or file name with strange number append, like a.mp4-85:56:23:42 wtf it is?
