### ISSUE TITLE
Folders (respectively files in it) cannot be dropped anymore

### ISSUE THREAD

**Issue by shell-er** [georgipeltekov/ngx-file-drop#272]
We upgraded the library recently to from 9.0.1 to 14.0.1. Single and multi file drops still work perfectly, but it does not allow to drop folders anymore. The folder is recognized as a file and therefor it does not search for files in it. See NgxFileDropEntry: 
![image](https://user-images.githubusercontent.com/118901077/203544676-643ced1a-8493-484c-b440-87169a19ff0f.png)

**Comment by georgipeltekov** [comment]
Hey, yes, unfortunately this is a regression , you can use version 14.0.0

**Comment by shell-er** [comment]
Thank you so much for this fast answer! We'll downgrade for now then

**Comment by georgipeltekov** [comment]
The regression should be fixed in the latest 14.0.2, pushed just now
