### ISSUE TITLE
How the get the real file reference from type File?

### ISSUE THREAD

**Issue by AndreasSchmid1** [georgipeltekov/ngx-file-drop#29]
I want to use the Html 5 File Api and use the function file.slice(startbyte,endbyte); The file ref available in the file.fileEntry is not working after it does not have a contentlength

**Comment by georgipeltekov** [comment]
You mean the size property? You can check the demo page. First the file must be read:

file.fileEntry.file(fileData => {
          console.log(fileData);
})

**Comment by AndreasSchmid1** [comment]
Thanks that was exactly what i was searching for

**Comment by rajpatelflynn** [comment]
I see the same issue of missing file type when I drag a file however, if i select a file (using the browse button then open), the file type is read correctly. How can I fix this?
See the screenshots attached for the different FileSystemFileEntry Objects
![WhenDroppingTheFile](https://user-images.githubusercontent.com/46640020/66436436-0d3ef580-e9f5-11e9-8385-ab5cee6d7846.png)
![WhenSelectingFile](https://user-images.githubusercontent.com/46640020/66436437-0dd78c00-e9f5-11e9-9148-14a044a87a28.png)
