### ISSUE TITLE
Server side file format

### ISSUE THREAD

**Issue by ademirqueiroga** [georgipeltekov/ngx-file-drop#3]
How can i handle the file in the server side (nodejs using express) ? If I send the file.fileEntry (as in example) when i log the fileEntry.file i got an undefined. How can i get the file itself ?

**Comment by georgipeltekov** [comment]
did you use file.fileEntry directly? You can check the example:
file.fileEntry.file(info => {
        console.log(info);
      });

getting the file info is async operation, so in the above example, the actual file will be the info variable. Check it and let me know if it works

**Comment by ademirqueiroga** [comment]
Oh, i didn't notice that... Now It's working as expected. I'm new with node and angular so still making a few mistakes.
Thank you!
