### ISSUE TITLE
Get File Base64 Format

### ISSUE THREAD

**Issue by dosama** [georgipeltekov/ngx-file-drop#30]
Is there is a way to get the file content in Base64 format from the file object ???
This is the info i get from the library  .. There is no any info describing the file content it self 
 
File(60005) {name: "profile (4).jpg", lastModified: 1511451066787, lastModifiedDate: Thu Nov 23 2017 17:31:06 GMT+0200 (Egypt Standard Time), webkitRelativePath: "", size: 60005, …}
lastModified:1511451066787
lastModifiedDate:Thu Nov 23 2017 17:31:06 GMT+0200 (Egypt Standard Time) {}
name:"profile (4).jpg"
size:60005
type:"image/jpeg"
webkitRelativePath:""

**Comment by georgipeltekov** [comment]
the file object use the standard html5 file api. So  you can convert the file in base 64 in the same way, as with the standard api. You can check this link for instace: https://stackoverflow.com/questions/36280818/how-to-convert-file-to-base64-in-javascript
