### ISSUE TITLE
Template parse errors: 'file-drop' is not a known element:

### ISSUE THREAD

**Issue by kirtikanna** [georgipeltekov/ngx-file-drop#31]
compiler.es5.js:1694 Uncaught Error: Template parse errors:
'file-drop' is not a known element:
1. If 'file-drop' is an Angular component, then verify that it is part of this module.
2. If 'file-drop' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
hardware
<div class="center">
  [ERROR ->]<file-drop headertext="Drop files here" (onFileDrop)="dropped($event)" 
  (onFileOver)="fileOver($ev"): ng:///AppModule/HardWareComponent.html@26:2
    at syntaxError (compiler.es5.js:1694)
    at TemplateParser.webpackJsonp.../../../compiler/@angular/compiler.es5.js.TemplateParser.parse (compiler.es5.js:12791)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileTemplate (compiler.es5.js:26994)
    at compiler.es5.js:26913
    at Set.forEach (<anonymous>)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileComponents (compiler.es5.js:26913)
    at compiler.es5.js:26800
    at Object.then (compiler.es5.js:1683)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler._compileModuleAndComponents (compiler.es5.js:26799)
    at JitCompiler.webpackJsonp.../../../compiler/@angular/compiler.es5.js.JitCompiler.compileModuleAsync (compiler.es5.js:26728)

I got this error.Help me to figure out on what mistake i did...
Thank you in Advance.

**Comment by georgipeltekov** [comment]
Did you include it in your app.module.ts file? Could you share, how did you include the library in your application?

**Comment by kirtikanna** [comment]
import{FormsModule}from'@angular/forms';
import{BrowserModule}from'@angular/platform-browser';
import{HttpModule,JsonpModule}from'@angular/http';
import{HardWareComponent}from'./../hardware/hardware.component';
import{NgModule}from '@angular/core';
import { FileDropModule } from 'ngx-file-drop';

@NgModule({
    declarations:[HardWareComponent],
    imports:[FormsModule,BrowserModule,HttpModule,JsonpModule,FileDropModule],
    bootstrap:[HardWareComponent]
})
export class HardwareModule{
   
}

**Comment by georgipeltekov** [comment]
Could you please provide reproducible repo or  some sandbox, like https://jsfiddle.net/

**Comment by kirtikanna** [comment]
https://plnkr.co/edit/S9nygxt4j3J5LsWtWKiO?p=preview

**Comment by georgipeltekov** [comment]
Hi, 
if you are using systemjs.config.js you should define the package there as well. Try adding:
ngx-file-drop': 'npm:ngx-file-drop/bundles/ngx-file-drop.umd.js',

where you define other umd.js files

**Comment by kirtikanna** [comment]
But i have that package in my project.
And i got the error for this line  
<file-drop headertext="Drop files here" (onFileDrop)="dropped($event)" 
    (onFileOver)="fileOver($event)" (onFileLeave)="fileLeave($event)">
        <span>optional content (don't set headertext then)</span>
    </file-drop>

when i remove the  **file-drop**  in html file then only that error disappear..

**Comment by georgipeltekov** [comment]
So you are importing the ngx-file-drop in the system.js.config? Could you please update the plnkr example ,because once this line is add in the file, the error is not shown anymore

**Comment by georgipeltekov** [comment]
Here you can check the sources of the demo page, that was created with angular-cli.
https://github.com/georgipeltekov/georgipeltekov.github.io/tree/master/sources

The error seems to be on your side, without a way or source code to reproduce it, there is nothing I can do more :(

**Comment by kirtikanna** [comment]
I solved by importing the FileDropModule  in app.module.ts
And also deleted the FileDropModule   module ( hardware.module.ts ) where i called the original Drop function.
finally that Worked..
And thanks georgipeltekov :)
