### ISSUE TITLE
Problem with fileupload

### ISSUE THREAD

**Issue by maxfrz21** [georgipeltekov/ngx-file-drop#34]
Hello, 

sorry I have a problem during fileupload with this module. 
After Drop file, the property "type" of file is null and i saw only information about name,size and lastModified... how can access to entire File with your module?

This is my code, it's correct? :

public dropped(event: UploadEvent) {
      var input = new FormData(); 
      if (event.files[0].fileEntry.file) {
        event.files[0].fileEntry.file(function (fileData) {
          input.append('uploadedFile', fileData);
        });
      }
      //this provide a rest multipart call 
      this.inserisciExcel(input);
  }

Thanks a lot for your fast help!!
Max

**Comment by georgipeltekov** [comment]
Hi,

please see issue #29

**Comment by maxfrz21** [comment]
Hi,

I've seen your code :

file.fileEntry.file(fileData => {
console.log(fileData);
})

but if i print this, i saw:

lastModified:1513847859322
lastModifiedDate:Thu Dec 21 2017 10:17:39 GMT+0100 (ora solare Europa occidentale) {}
name:"prova.xls"
size:49152
type:""
 
type is udefined, his value maybe set to "application/vnd.ms-excel" ?

Max

**Comment by georgipeltekov** [comment]
Hi,

sorry I misunderstand your questions initially. Unfortunately this is limitation of the file api itself. You can check here:
https://developer.mozilla.org/en-US/docs/Web/API/File/type

and more concrete:
"Note: Based on the current implementation, browsers won't actually read the bytestream of a file to determine its media type. It is assumed based on the file extension; a PNG image file renamed to .txt would give "text/plain" and not "image/png". Moreover, file.type is only reliable for common file types like images, documents audio and video. Uncommon file extensions would return an empty string. Developers are advised not to rely on this property as a sole validation scheme."

**Comment by maxfrz21** [comment]
Hi

thanks, i can force his value?
if i use a normal input type file type is set correctly.. thanks a lot!

Max

**Comment by rajpatelflynn** [comment]
I see the same issue of missing file type when I drag a file however, if i select a file (using the browse button then open), the file type is read correctly. How can I fix this?
See the screenshots attached for the different FileSystemFileEntry Objects
![WhenDroppingTheFile](https://user-images.githubusercontent.com/46640020/66436436-0d3ef580-e9f5-11e9-8385-ab5cee6d7846.png)
![WhenSelectingFile](https://user-images.githubusercontent.com/46640020/66436437-0dd78c00-e9f5-11e9-9148-14a044a87a28.png)

**Comment by georgipeltekov** [comment]
as mentioned above this is limitation of how the different browsers use the file api. You can use the file extension for such cases
