### ISSUE TITLE
preview uploaded images

### ISSUE THREAD

**Issue by alireza-saberi** [georgipeltekov/ngx-file-drop#36]
I am trying to preview images that are uploaded, It that possible via your component?

**Comment by georgipeltekov** [comment]
Hi 
yes, it is possible. Basically after you read the file you have the freedom to use it as you wish. The very standard way to use it is something like that (taken from here: https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL)


```
file.fileEntry.file(info => {
        console.log(info);
        var reader = new FileReader();
        var preview = document.querySelector("img");
        reader.addEventListener("load", function () {
          preview.src = reader.result;
        }, false);
        reader.readAsDataURL(info);
      });
```


having `<img src="" style="width: 100px; height: 100px"/>`

somewhere in the html. (this is just an example usage. Basically the first image will be shown, however I think you got the idea.)
