### ISSUE TITLE
Use really only the customStyle if it is given

### ISSUE THREAD

**Issue by Joniras** [georgipeltekov/ngx-file-drop#37]
I have a lot of html inside the file-drop element and it gets styled because of this content class, my solution:

```html
//file-drop.component.html:4
<div [class.content]="!customstyle">
```

i could not create a pull request (i tried but i may be too inexperienced in github) but i would be pleased if you could change this.

**Comment by georgipeltekov** [comment]
Hi, thank you for your contribution. However I am not sure what is the problem.  Do you want to use the customstyle or not. If not, just don't pass the attribute. If yes, you can check also this #21 for some guidance. You can check also #9

**Comment by Joniras** [comment]
Ok sorry, my title is maybe a bit misleading, the more specific and correct version would be:

Dont set the class "content" (because it has predefined styles in the library) if a customstyle attribute is given.

So my problem was, that i have my file-drop element and in there i have lots of html (some buttons, some flexLayout attributes, text, maybe an image, and so on). If i now watch the output in the browser, all the text is blue, my height is limited to 100px etc.. 
Although i set a custom Class. 

My **expected behaviour** would be, that no styles are applied if i set th customstyle attribute.

I already did a pull-request on that: #38

**Comment by georgipeltekov** [comment]
Hey,

oh ok, I got your point now. Unfortunately I think that will break the already installed apps, when the users rely on the default styling. This was also the initial idea - to provide some default styling, that could be easily be overwritten,Probably you can workaround the issue by overwriting #dropZone.drop-zone in the styles.scss.

**Comment by Joniras** [comment]
That it will break existing apps is actually a good point, i can understand that.

 **I will do a workaround instead.**

Thanks for the support anyway.
