### ISSUE TITLE
Multiple file-drops on same page

### ISSUE THREAD

**Issue by jacobbutton** [georgipeltekov/ngx-file-drop#39]
I can't get multiple instances of `<file-drop>` on the same page to work correctly. 

The onFileDrop event only fires for the last instance of `<file-drop>`.

**Comment by georgipeltekov** [comment]
Hi ,
I didn't quite get you. Could you please provide some sources, where the issue could be reproduced?

**Comment by jacobbutton** [comment]
Sorry, my post wasn't displaying correctly. I've updated it. Does it make sense now?

**Comment by georgipeltekov** [comment]
Yes, it makes sense now. Are you sure you are using separate objects and functions for the different instances? I just modified the sandbox and it seems to work fine (I can drop files to both areas and the files are displayed correctly):
```
<div class="center">
    <file-drop headertext="Drop files here" (onFileDrop)="dropped($event)" (onFileOver)="fileOver($event)" (onFileLeave)="fileLeave($event)"></file-drop>
    <div class="upload-table">
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody class="upload-name-style">
                <tr *ngFor="let item of files; let i=index">
                    <td><strong>{{ item.relativePath }}</strong></td>
                </tr>
            </tbody>
        </table>
    </div>

    <file-drop headertext="Drop files here" (onFileDrop)="dropped2($event)" (onFileOver)="fileOver2($event)" (onFileLeave)="fileLeave2($event)"></file-drop>
    <div class="upload-table">
        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody class="upload-name-style">
                <tr *ngFor="let item of files2; let i=index">
                    <td><strong>{{ item.relativePath }}</strong></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
```


```
import { Component } from '@angular/core';
import { UploadFile, UploadEvent } from '../../lib/ngx-drop';

@Component({
  selector: 'demo-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  public files: UploadFile[] = [];

  public files2: UploadFile[] = [];

  public dropped(event: UploadEvent) {
    this.files = event.files;
    for (const file of event.files) {
      file.fileEntry.file(info => {
        console.log(info);
      });
    }
  }

  public dropped2(event: UploadEvent) {
    this.files2 = event.files;
    for (const file of event.files) {
      file.fileEntry.file(info => {
        console.log(info);
      });
    }
  }

  public fileOver(event) {
    console.log(event);
  }

  public fileOver2(event) {
    console.log(event);
  }

  public fileLeave(event) {
    console.log(event);
  }

  public fileLeave2(event) {
    console.log(event);
  }
}

```

**Comment by jacobbutton** [comment]
Here's a plunker of the issue

https://plnkr.co/edit/OBdgdLJ9ohedqIMNrNF1?p=preview

**Comment by jacobbutton** [comment]
I just saw your last response.  That really isn't a solution for multiple reasons. I should be able to use the same function for multiple file-drops, the function shouldn't care what object is calling it.

**Comment by jacobbutton** [comment]
Here's another plunker better demonstrating the issue. Even when the file-drops are in their own separate components, it doesn't work. This makes it very difficult to build things like content generated document libraries with hierarchical directory structures. I can't have a separate upload event function for every single file-drop. However, it should work even if they were in the same component.

https://plnkr.co/edit/9Y3mTW0aS0xmRIQZu9jJ?p=preview

**Comment by jacobbutton** [comment]
It should work with nested file-drops as well, not just sibling file-drops.  That use case isn't presented in the plunker, but it will be used in my application.

I'm trying to setup and file upload drag and drop similar to way google drive drag and drop works. The ability to drop into a parent, as well as individual child containers.

**Comment by georgipeltekov** [comment]
ok I understand your problem now. Unfortunately the described use case by you works only for files and not for folders, as for folders there are some restrictions that we cannot workaround. If you test your examples with files, you will see that is is working fine. As a workaround you can try to have different definitions of a functions that all are calling  one main upload method.
