### ISSUE TITLE
Angular 5 support

### ISSUE THREAD

**Issue by jhossy** [georgipeltekov/ngx-file-drop#40]
Hi!

Thank you for an awesome project - keep up the good work!

I get the following error in a completely fresh Angular 5 project: (following your tutorial on install)

Uncaught Error: Template parse errors:
'file-drop' is not a known element:
1. If 'file-drop' is an Angular component, then verify that it is part of this module.
2. If 'file-drop' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<div class="center">

Sorry, if this is not the correct place to report bugs.

**Comment by georgipeltekov** [comment]
Could you please provide some source code, where the issue could be reproduced. The library works on angular 5, so most probably you didnt define something somewhere. You can also check the sandbox example in the library

**Comment by AlexKhymenko** [comment]
@jhossy You forgot to add the library to you module.

**Comment by jhossy** [comment]
This is my source code:

**app.module.ts:**

`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }`

**app.component.ts:**

`import { Component } from '@angular/core';
import { UploadEvent, UploadFile } from 'ngx-file-drop';

@Component({
  selector: 'demo-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  public files: UploadFile[] = [];

  public dropped(event: UploadEvent) {
    this.files = event.files;
    for (const file of event.files) {
      file.fileEntry.file(info => {
        console.log(info);
      });
    }
  }

  public fileOver(event){
    console.log(event);
  }

  public fileLeave(event){
    console.log(event);
  }
}`

**app.component.html:**

`<div class="center">
  <file-drop headertext="Drop files here" (onFileDrop)="dropped($event)" 
  (onFileOver)="fileOver($event)" (onFileLeave)="fileLeave($event)">
      <span>optional content (don't set headertext then)</span>
  </file-drop>
  <div class="upload-table">
      <table class="table">
          <thead>
              <tr>
                  <th>Name</th>
              </tr>
          </thead>
          <tbody class="upload-name-style">
              <tr *ngFor="let item of files; let i=index">
                  <td><strong>{{ item.relativePath }}</strong></td>
              </tr>
          </tbody>
      </table>
  </div>
</div>`

**Comment by jhossy** [comment]
That error was on me. Re-doing the project from scratch made it work.

Thanks for the help.
