### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by rcristaldi** [georgipeltekov/ngx-file-drop#42]
Hi, I was looking for some component to quickly navigate a file system, and yours is really fast!!!
But I can't upload a file :-(
I'm using angular 4 and  formData, somethink like this:

 formData.append(`files`, file.fileEntry.resultFile, file.relativePath);

but it seem not work. Can you help?
thanks.

**Comment by jacobbutton** [comment]
Would you mind posting the code for the whole function? Might be valuable to give some more info/code on how you're handling the file info on the whatever backend you're using as well.

What you've posted so far isn't enough to go off of.

**Comment by rcristaldi** [comment]
hi, here the code:


@Component({
  selector: 'app-upload',
  templateUrl: './upload.html',
  styleUrls: ['./upload.css']
})

export class UploadComponent {

  constructor(private http: HttpClient) {}

  
  public files: UploadFile[] = [];

  
  uploadHandlerFiles2() {
      let formData = new FormData();

    for (let file of this.files) {
      
      let f;
      file.fileEntry.file(info => f);
      formData.append(`files`, f, f.name);

    }

    this.http.post('http://localhost:8080/rest/upload/files', formData).subscribe(() => console.log("request done with success"));

  }

  public dropped(event) {
    console.log('drop');
    this.files = event.files;
    for (let file of event.files) {
        file.fileEntry.file(info => {console.log(info);});
    }
}

  public fileOver(event){
    console.log(event);
  }

  public fileLeave(event){
    console.log(event);
  }

----------------------
I know there is someting wrong here: 
 for (let file of this.files) {     
      let f;
      file.fileEntry.file(info => f);
      formData.append(`files`, f, f.name);
  }

but I've tried lots of variants with no success :-(

**Comment by jacobbutton** [comment]
You should be handling the files in the dropped event.  You also need to wait for `file.fileEntry.file(info => {}) ` to finish before pushing your formData to the server. Try this.
```
@Component({
	selector: 'app-upload',
	templateUrl: './upload.html',
	styleUrls: ['./upload.css']
})
export class UploadComponent {

	constructor(private http: HttpClient) {}

	public dropped(event) {
		let formData = new FormData();
		for (let i = 0; i < event.files.length; i++) {
			event.files[i].fileEntry.file(file => {
				formData.append("files", file, event.files[i].relativePath);
				if (i === event.files.length - 1) {
					this.http.post('http://localhost:8080/rest/upload/files', formData)
						.subscribe(() => console.log("request done with success"));
				}
			});
		}
	}

	public fileOver(event) {
		console.log(event);
	}

	public fileLeave(event) {
		console.log(event);
	}
}
```

**Comment by georgipeltekov** [comment]
As @jacobbutton mentioned, you need  to wait for file.fileEntry.file(info => {}) to finish before pushing your formData to the server.

**Comment by rcristaldi** [comment]
Great! It's work.
Thanks very much.
