### ISSUE TITLE
In IE 11 is not working

### ISSUE THREAD

**Issue by luis-teixeira** [georgipeltekov/ngx-file-drop#45]
Unfortunately I have to have support for IE11. My Client uses IE11. 
At this point there is a bug when a file is dropped into the dropzone.
Can you help me?

ERROR TypeError: Unable to get property 'isFile' of undefined or null reference

**Comment by georgipeltekov** [comment]
what version of the library are you using? Also a stack trace would be helpful

**Comment by luis-teixeira** [comment]
Hello @georgipeltekov 
I'm using "ngx-file-drop": "2.0.1",
Here a screen shot of Stack trace

![screenshot](https://user-images.githubusercontent.com/3420791/36153374-f08cc7e6-10c5-11e8-8197-35cfec1d1728.png)

IE sucks :(

**Comment by georgipeltekov** [comment]
please try with the latest version.

**Comment by luis-teixeira** [comment]
I'm very ashamed
I should have noticed that I did not have the latest version.
dead lines ....: S
Thank you so much for the speed of your help.
Keep up the good work.
