### ISSUE TITLE
 error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

### ISSUE THREAD

**Issue by utnas** [georgipeltekov/ngx-file-drop#47]
## I'm submitting a...

[] Regression (a behavior that used to work and stopped working in a new release)
**[x ] Bug report**  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

### Current behavior
From Angular 5.1.3 and before my compilation problem worked fine. Upon upgrading to 5.2.2 I now get ...

ERROR in /ngx-file-drop/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11)
TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

ERROR in Error during template compile of 'FileDropModule'
  Function expressions are not supported in decorators in 'NgModule'
    'NgModule' contains the error at ../@angular/core/core.ts(194,31)
      Consider changing the function expression into an exported function.
node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-file-drop/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

### Expected behavior
No compilation error.

### Solution
https://github.com/angular/angular-cli/issues/9464
https://github.com/angular/angular/issues/21925

What is the motivation / use case for changing the behavior?
Broken

### Environment

Angular version: 5.2.1
 
For Tooling issues:
- Node version: 8.2.1
- Platform:  Mac

Others:

**Comment by georgipeltekov** [comment]
Hey, what version of the library are you using?

**Comment by serkansokmen** [comment]
Same here, using v2.0.5 (Interestingly this is not in release, but yarn installed 2.0.5 automatically)
Tried downgrading to v2.0.4, still the same :(

Also Angular is v5.2.6

**Comment by georgipeltekov** [comment]
Hmm strange. I just tested it, here is my package.json:

```
{
  "name": "test-prj",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^5.2.6",
    "@angular/compiler": "^5.2.6",
    "@angular/core": "^5.2.6",
    "@angular/forms": "^5.2.6",
    "@angular/http": "^5.2.6",
    "@angular/platform-browser": "^5.2.6",
    "@angular/platform-browser-dynamic": "^5.2.6",
    "@angular/router": "^5.2.6",
    "core-js": "^2.5.3",
    "ng2-table": "^1.3.2",
    "ngx-bootstrap": "^1.9.3",
    "ngx-file-drop": "^2.0.5",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.20"
  },
  "devDependencies": {
    "@angular/cli": "^1.7.1",
    "@angular/compiler-cli": "^5.2.6",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.101",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "^1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "link": "^0.1.5",
    "npm": "^5.6.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.6.1",
    "webpack": "^3.11.0"
  }
}

```

and it runs without a problem. Could you try to remove package-lock.json and node_modules folder, run npm install and try agaian

**Comment by serkansokmen** [comment]
Yes, it seems like working now with a fresh install of `"ngx-file-drop": "^2.0.5",` even without removing lock files or node_modules dir, thanks :)
