### ISSUE TITLE
Angular 5.2.7: No Provider for NgZone

### ISSUE THREAD

**Issue by SnickersFromMars** [georgipeltekov/ngx-file-drop#48]
I get the following error and i can't figure out why:

`FileDropComponent.html:2 ERROR Error: StaticInjectorError(AppModule)[FileComponent -> NgZone]: 
  StaticInjectorError(Platform: core)[FileComponent -> NgZone]: 
    NullInjectorError: No provider for NgZone!
    at _NullInjector.get (core.js:1002)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.get (core.js:1110)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1242)
    at StaticInjector.get (core.js:1110)
    at resolveNgModuleDep (core.js:10854)
    at NgModuleRef_.get (core.js:12087)
    at resolveDep (core.js:12577)`

dependencies:
`    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "core-js": "^2.4.1",
    "ngx-file-drop": "^2.0.5",
    "primeng": "^5.2.0",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"`

Angular version: 5.2.7

**Comment by georgipeltekov** [comment]
could you please share reproducible source

**Comment by SnickersFromMars** [comment]
[https://github.com/SnickersFromMars/FileDropTest](url)

tell me when u downloaded the test-repo. i'll delete it then

**Comment by georgipeltekov** [comment]
Your repo works just fine! I clone it and run npm install, after that I manage to run the application (there were some errors due to missing css files, but this is not related to the library). You can check whether you have same discrepancies in your angular version, global angular-cli version or something like that.  Ensure you are using the latest.

**Comment by SnickersFromMars** [comment]
ng -v:

@angular/cli: 1.7.2
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

**Comment by georgipeltekov** [comment]
did you try to clone your repo on new location and run it after clean new npm install

**Comment by SnickersFromMars** [comment]
done,

same error... :cry:

**Comment by georgipeltekov** [comment]
I cannot do anything if I am not able to reproduce the error. You can try to setup plunker or stackblitz where I can look at

**Comment by georgipeltekov** [comment]
You can check here: https://stackblitz.com/edit/angular-awlfv4
I also see that you are mentioning angular 5.2.7 but in the same time I see that you are using 5.2.0. While creating the stackblitz example I face some similar error. What I did to fix it (as it was referencing to angular core 5.0.0 ) I remove the dependencies and add it again in order  to install the latest one - 5.2.7

**Comment by Michalwisniewski1** [comment]
Hi, unfortunatelly I've got the same error as above

`Error: Uncaught (in promise): Error: StaticInjectorErrorAppModule)[FileComponent -> NgZone]: 
  StaticInjectorError(Platform: core)[FileComponent -> NgZone]: 
    NullInjectorError: No provider for NgZone!
Error: StaticInjectorError(AppModule)[FileComponent -> NgZone]: 
  StaticInjectorError(Platform: core)[FileComponent -> NgZone]: 
    NullInjectorError: No provider for NgZone!`

**Comment by georgipeltekov** [comment]
Please provide reproducible example. You can check my stackblitz from the previous response

**Comment by jacobbutton** [comment]
I've been having the same error for about the past few weeks after upgrading angular. I think there's a conflict between my applications angular version and the angular version of ngx-file-drop.

The work around I've been using so far is removing ngx-file-drop's node_modules folder before running webpack and compiling my application.

**Comment by elzebu** [comment]
For information, I had the same issue here. I'm using webpack as @jacobbutton to compile my project. Delete manually the node_modules folder from the ngx-file-drop directory works locally, but it's not a suitable solution in our devops context... I've updaded angular from 5.1 to 5.2 (following this instructions : https://angular-update-guide.firebaseapp.com/) and it works fine now.
Thanks for your works !
