### ISSUE TITLE
Unable to update view on drop file

### ISSUE THREAD

**Issue by MansoorAhmed70** [georgipeltekov/ngx-file-drop#49]
Hi,
I am unable to update the view after reading the file. please find the code below.

  public dropped(event: UploadEvent) {
    const _t = this;
    const imageTypes = ['png', 'svg', 'jpg', 'jpeg', 'jfif', 'jpe'];
    this.files = event.files;
    for (const file of event.files) {
      file.fileEntry.file(info => {
        const fileOnlyImage = info.type.split('/')[1].toLowerCase();
        if (imageTypes.indexOf(fileOnlyImage) !== -1) {
          this.imageFlag = true;//unable to update the imageFlag in view
        }
      });
    }
  }

**Comment by georgipeltekov** [comment]
Hi, I didnt quite understand what is the problem. Is there any error, what happens in the view. Also please provide some reproducible example. You can use stackblitz for instance, it is easy and quick to create examples there

**Comment by MansoorAhmed70** [comment]
Hi In view HTML
<div *ngIf="imageFlag">
--some content --
</div>
when i update the imageFlag from dropped even inside .file the imageFlag is not updating in view

**Comment by georgipeltekov** [comment]
I dont see how this is connected with the used library it is rather development tasks.

**Comment by joscampbell** [comment]
Did you figured this out?. I notice that the view only updates when you click off focus..

**Comment by georgipeltekov** [comment]
I dont think this is connected with the library at all, but it is rather a development task. At least could you please provide stackblitz reproducible example

**Comment by georgipeltekov** [comment]
You can check also #51
