### ISSUE TITLE
Missing correct absolutePath

### ISSUE THREAD

**Issue by ddobric** [georgipeltekov/ngx-file-drop#5]
Absolute path seems to be always relative path.
Bug or feature?

Any sample, which shows how to read file?

**Comment by georgipeltekov** [comment]
Did you check the readme file?
There is an example method that shows how to read file:
public dropped(event: UploadEvent) {
    this.files = event.files;
    for (var file of event.files) {
      file.fileEntry.file(info => {
        console.log(info);
      });
    }
  }

**Comment by georgipeltekov** [comment]
closing as there is no response from the author
