### ISSUE TITLE
Cannot get data refreshed inside fileEntry.file((file: File) => {...} )

### ISSUE THREAD

**Issue by julialabish** [georgipeltekov/ngx-file-drop#51]
Hello,
trying to upload file, and after upload success -> refreshing data

```
fileEntry.file((file: File) => {
          const formData = new FormData();
          formData.append('property1', '1');
          formData.append('property2, 'false');
          formData.append('Files', file, file.name);

          this._myHttpService.add(formData).subscribe(() => {
            this.toast.info('Document successfully created.');
            this.refreshData();
          });
        });
```

```
refreshData() {
    this._myHttpService.getData().subscribe(documents=> {
      this.documents = documents
    });
  }
```

```
<file-drop (onFileDrop)="dropped($event)" (onFileOver)="fileOver($event)" (onFileLeave)="fileLeave($event)" customstyle="my-drop-zone">
    <div class="container-fluid">
      <div class="row m-3">
        <div class="col-sm-6">
          <h3>Documents</h3>
          <ul class="list-group">
            <li class="list-group-item" *ngFor="let document of documents">  <-- **this list is not refreshed**
{{document.Name}}
            </li>
          </ul>
        </div>
      </div>
    </div>
  </file-drop>
```

strange thing about it is, when I'm dragging file over again, list refreshes....

**Comment by georgipeltekov** [comment]
Could you please create a reproducible examples somewhere. You can check stackblitz for instance

**Comment by julialabish** [comment]
something like this [](https://stackblitz.com/edit/angular-jstkxu) but I cannot get FileDropModule dependency to work

**Comment by georgipeltekov** [comment]
You can check this one:
https://stackblitz.com/edit/angular-a3avvv

Basically you need to mark the changes for refresh. But keep in mind to do this only when needed and not on every iteration as it is a heavy operation (i just put it this way for simplicity)

Check these lines:

```
this.ref.markForCheck();
this.ref.detectChanges()
```

**Comment by julialabish** [comment]
Thank you!

**Comment by mshubin** [comment]
Hi,

I had the same issue. And even with `this.ref.markForCheck()` and `this.ref.detectChanges()` my other component displaying the list of dropped documents wasn't refreshed.

Solved it by using NgZone:
```
this.zone.run(() => {
    this.documents = [{ name: 'doc3' }, { name: 'doc4' }, { name: 'doc5' }];
});
```

Maybe it can help someone else, who knows :)
