### ISSUE TITLE
How do you drag multiple files?

### ISSUE THREAD

**Issue by joscampbell** [georgipeltekov/ngx-file-drop#53]
I want to allow the user to drag and drop up to 5 images. That would be stored in files array.. then uploaded to server.

Current the image object is replaced after every file drop.

**Comment by georgipeltekov** [comment]
Can you share a stackblitz example or some sources about that. Basically you can drag and drop multiple files and whole folders. You can check at the demo in the description. Also if you check the readme you will see in the code examples that there is a for loop where we can iterate over all the dragged files.

**Comment by georgipeltekov** [comment]
Closing as no additional info was provided.

**Comment by larearruda** [comment]
Hi. I checked the demo in description as you mentioned (on this link https://georgipeltekov.github.io/) and I was not able to upload multiple files. Table 'upload-name-style' only keeps one file. My code is the exactly the same provided on example.

**Comment by georgipeltekov** [comment]
Can you at least provide some code and a stackblitz example? I cannot know what you did otherwise @larearruda . Here , you can check this example:
https://stackblitz.com/edit/angular-blhb9x

**Comment by larearruda** [comment]
My template 

`    <div class="form-group">

        <file-drop dropZoneLabel="Drop files here" (onFileDrop)="dropped($event)" 
        (onFileOver)="fileOver($event)" (onFileLeave)="fileLeave($event)">
            <span>Drag and drop files here</span>
        </file-drop>
        <div class="upload-table">
            <table class="table">
                <thead>
                    <tr>
                        <th>File Name</th>
                    </tr>
                </thead>
                <tbody class="upload-name-style">
                    <tr *ngFor="let item of files; let i=index">
                        <td><strong>{{ item.relativePath }}</strong></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>`

In the example you provided is happening the same thing:  object is replaced after every file drop.

**Comment by georgipeltekov** [comment]
yes, because you dont save the state of the previous items. In order to save them, just copy the dropped files in another list, use the second list to show it in your table and you are ready to go. this is not related with the library, but rather it is a dev tasks

**Comment by larearruda** [comment]
thanks, will try that!
