### ISSUE TITLE
file-drop' is not a known element

### ISSUE THREAD

**Issue by KumailHussain** [georgipeltekov/ngx-file-drop#64]
file-drop' is not a known element:
1. If 'file-drop' is an Angular component, then verify that it is part of this module.
.......

I am using angualr 5
`"dependencies": {
    "@angular/animations": "^5.2.10",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "angular-font-awesome": "^3.1.2",
    "bootstrap": "^4.1.0",
    "cfenv": "^1.0.4",
    "core-js": "^2.4.1",
    "express": "^4.15.0",
    "font-awesome": "^4.7.0",
    "ngx-file-drop": "^3.0.0",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  `
and using version 3.0.0

I have added to app.module.ts too but still facing error

**Comment by georgipeltekov** [comment]
As I commented in the previous ticket, if you want to use it with angular 5 you need to use older version of the library - 3.0.2 or less. In the dependencies you have put "ngx-file-drop": "^3.0.0". This does not mean that you are using the version 3.0.0. The ^ sign means "takes the latest version after 3.0.0". So in that case you have taken the latest, which is 4.0.0. If you want to use specific version of the library (this is valid for all libraries, it is how angular works), just remove the ^ sign. After that you can npm install to install the exact that version (to be on the same side you can delete the whole node_modules before that)

**Comment by brandonburns** [comment]
This is still happening for me. I am using angular 6. I have tried all versions 4.0.0 - 4.0.6 which claim to be for Angular 6. I made sure the ^ was removed from package json. I have deleted node_modules and ran npm install multiple times. Still has the same error in the console, file-drop is not a known element
