### ISSUE TITLE
Error during template compile

### ISSUE THREAD

**Issue by adskiremote** [georgipeltekov/ngx-file-drop#67]
Hi I was testing angular-cli build - Version 6.0.0 and am getting this error...

ERROR in ngx-file-drop\ngx-file-drop.ts(4,2): Error during template compile of 'FileDropModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.

Do you have any suggestions?

**Comment by georgipeltekov** [comment]
you can check #61. try to remove the node modules folder. If this does not help, please provide reproducible example. You can check the stackblitz one in #61

**Comment by adskiremote** [comment]
Many thanks Georgi missed that one.  Much appreciated.
