### ISSUE TITLE
Broken demo

### ISSUE THREAD

**Issue by astr0sl0th** [georgipeltekov/ngx-file-drop#72]
Using Angular 6 your demo appears to be broken

**Comment by georgipeltekov** [comment]
I didnt quite understand , which demo is broken with Angular 6. Did you use the code example from the readme file?

**Comment by astr0sl0th** [comment]
I followed the readme file exactly and get the following error:

![screen shot 2018-05-16 at 09 47 56](https://user-images.githubusercontent.com/9317246/40106695-50860192-58ee-11e8-85d7-7213ed530df7.jpg)

**Comment by georgipeltekov** [comment]
try to remove the node_modules folder inside ngx-file-drop. you can refer here #61 
I am almost done with the fix, it will be out shortly

**Comment by astr0sl0th** [comment]
@georgipeltekov Thanks 👍

**Comment by astr0sl0th** [comment]
This is still failing to build:

`Module build failed: Error: ENOENT: no such file or directory, open '/Users/joe/projects/verado/node_modules/ngx-file-drop/node_modules/@angular/core/fesm5/core.js'`

**Comment by georgipeltekov** [comment]
please check the latest version 4.0.4

**Comment by georgipeltekov** [comment]
the stackblitz is fine:
https://stackblitz.com/edit/angular-k4emfw

I am closing this one, lest me know if there are any problems and we can reopen it again
