### ISSUE TITLE
angular 6 - customstyle is not getting applied

### ISSUE THREAD

**Issue by varundevappsys** [georgipeltekov/ngx-file-drop#76]
If I dont specify customstyle then the default style of blue dotted lines is shown.
If I specify the parameter then the class="class-name" appears on the source code  but the style is not applied.
Edit:
This happens only when we put the style-class inside component CSS. (Due to component level isolation)
The styles in the main CSS file works fine.

**Comment by georgipeltekov** [comment]
The custom style should be in the global css class declarations. You can check #60 or #65
