### ISSUE TITLE
NullInjectorError: No provider for NgZone!

### ISSUE THREAD

**Issue by vinaysimharaju** [georgipeltekov/ngx-file-drop#77]
Hi,
I am getting the below issue when I use this pacakage

NullInjectorError: No provider for NgZone!

when I place 
 <file-drop headertext="Drop files here" (onFileDrop)="dropped($event)"
                   (onFileOver)="fileOver($event)" (onFileLeave)="fileLeave($event)">
            <span>optional content (don't set headertext then)</span>
        </file-drop>

in the HTML and run the application.

**Comment by georgipeltekov** [comment]
what angular version and library version are tou using. Could you please provide stackblitz example? If you are using Angular 6+ you need to use the library version after 4.0.0, otherwise you need to use older version. 
You can check this example:
https://stackblitz.com/edit/angular-k4emfw

**Comment by georgipeltekov** [comment]
closing as no further info is provided. Please feel free to comment
