### ISSUE TITLE
How add content type validation using ngx-file-drop 

### ISSUE THREAD

**Issue by bhavinshiroya1994** [georgipeltekov/ngx-file-drop#80]
i have check file type on file drop time please let me know any validation parameter are available in file drop directive ?

**Comment by georgipeltekov** [comment]
I didnt quite get your point. However you can check the demo here: https://georgipeltekov.github.io/
If you drop a file and open the console you see the parameters of the dropped file (dumped in the console). There is a type property you can check and validate. If for some reason you want to skip this file, just skipped it.

**Comment by bhavinshiroya1994** [comment]
public droppedFile(event: UploadEvent) {
        console.log('event=====', event);
        this.fileModified = true;
        for (let file of event.files) {
            file.fileEntry.file(info => {
                this.corpoPresentationFile.nativeElement.value = '';
                console.log('info====', info);
                if(!this.checkFileUploadType(info.type)) {
                    return;
                }
                console.log('it is in filechanged======', info);
                this.dragDropFiles = info;
                this.ngZone.run(() => {
                    this.fileToUploadName = info.name;
                    this.fileUploadModal.hide();
                })
            });
        }
    }

public checkFileUploadType(type: any, isImageUpload:boolean = false) {
	
		console.log('type====', type);
		let typeArray = [];
			typeArray = ['image/jpeg', 'image/png', 'image/gif', 'image/svg+xml', 'image/bmp',
						'application/msword', 'application/pdf', 'text/plain', 'application/rtf',
						'application/vnd.ms-excel', ];
	
		if(typeArray.indexOf(type) > -1) {
			alert("successfully upload file");               
			return true;
		} else {
			alert("Not a valid file type");               
			return false;
		}

	}
above implement code but .csv file upload but getting file type is blank please let me know how to check csv file validation ?

**Comment by georgipeltekov** [comment]
For some file extension there is a browser specific and file API specific limitation, so you must handle situation where the type param is empty:

https://developer.mozilla.org/en-US/docs/Web/API/File/type

Different browsers will behave differently for this parameter. This is not connected with the library, but rather with the HTML 5 File API

**Comment by bhavinshiroya1994** [comment]
ok i will manage. your package ngx-file-drop is awesome but please added valiation functionality like this package https://github.com/leewinder/ng2-file-drop/tree/master.

thanks for quickly reply.
