### ISSUE TITLE
Big folder structure, not all files are uploaded

### ISSUE THREAD

**Issue by PhlppKnst** [georgipeltekov/ngx-file-drop#81]
Hi,

when I drop a bigger folder structure with 1200 files and 800 folders, not all files are found.
The subscription in line 128 of the file-drop.component.ts ends too early.
If I remove "this.subscription.unsubscribe();" it works, I get four chunks of arrays with files.
This means that the stack could be empty several times before all the files are read.
How can I build the package? Maybe I could fix this.

Best,
Philipp

**Comment by georgipeltekov** [comment]
You can create a pull request and I will check it.  I dont think it is a good option to remove "this.subscription.unsubscribe();" completely , as in this way we will send a lot of not needed events to the application that use the library. Probably we need additional check around the unsubscribe method.

p.s. if you are about to create a pull request please update the package.json file with the new version of the library, as well the readme file.

**Comment by georgipeltekov** [comment]
version 4.0.6 is published (there was a small fix I have to apply to your changes)

**Comment by nethore** [comment]
Hi,
I was wondering if you would provide any updates for older versions of Angular (4&5).
I'm experiencing the same problem but cannot update for the moment to Angular 6 because of old libraries.

Thanks in advance.

**Comment by georgipeltekov** [comment]
Hi, unfortunately this is not an option. You can fork and build it locally.

**Comment by nethore** [comment]
Ok thanks for your quick reply
