### ISSUE TITLE
(feature-request): filetype whitelist/blacklist

### ISSUE THREAD

**Issue by moshejs** [georgipeltekov/ngx-file-drop#83]
Hello,
I am writing to request an enhancement where one can allow/block certain file types (images: png, jpeg, pdf, txt, etc.)

**Comment by raamkumaarb** [comment]
I also need that file type restriction. When can we expect that?

**Comment by georgipeltekov** [comment]
You can easily handle that case in your part of the application. Once you receive the files from the library and iterate them, just skip the ones you dont need

**Comment by moshejs** [comment]
> You can easily handle that case in your part of the application. Once you receive the files from the library and iterate them, just skip the ones you dont need

Is there a reason you are against enhancing your popular plugin?

**Comment by angelayanpan** [comment]
that's a function that's 10 lines of code. list of supported extensions should be controlled by the application in a common location. not in the file-drop directive

**Comment by nfourie-work-profile** [comment]
> that's a function that's 10 lines of code. list of supported extensions should be controlled by the application in a common location. not in the file-drop directive

I disagree a little bit. I think that a "file upload" component should be able to specify which types it allows or disallows and ignores it from the base level. Similar to the functionality that is provided by the file-drop component [here](https://www.npmjs.com/package/ng2-file-drop). This component does not work as well as the ngx-file-drop and I prefer this one, but it's some food for thought.

**Comment by vvolodin** [comment]
The most common use-case includes limiting file types in the browse dialog as well. I don't see a way to do it using this component. Being able to limit the file picker to a single file wouldn't hurt either.

**Comment by sante85** [comment]
#127

**Comment by georgipeltekov** [comment]
version 5.0.6
