### ISSUE TITLE
Lack of mobile support

### ISSUE THREAD

**Issue by moshejs** [georgipeltekov/ngx-file-drop#86]
I realize this won't work for mobile devices as they cannot physically "Drag and drop" content.

I believed a workaround using  `<input type="file" (change)="dropped($event)">` would be sufficient, however `UploadEvent` type is not the same as `change` event type.

**Comment by moshejs** [comment]
I came up with my own workaround, for now. However, it would be nice to be able to use UploadEvent type
```
  public dropped(event: any) {
        if (event.type === 'change') {
            for (const file of event.target.files) {
                file.relativePath = file.name;
                fileList.push(file);
            }
        } else {
        ....default dropped code.....
        }
    }
```

**Comment by yglodt** [comment]
On the same subject, it would be useful to have the file-picker opening when clicking on the drag-zone.

That would also resolve this issue since on mobile this will typically trigger a dialog where you can either use the camera or pick a file from the device to upload.

**Comment by yglodt** [comment]
@moshejs Does your workaround also allow triggering the filepicker dialog by clicking on the drop-zone?

**Comment by moshejs** [comment]
> @moshejs Does your workaround also allow triggering the filepicker dialog by clicking on the drop-zone?

Yes, that's what <input type="file"> allows

**Comment by georgipeltekov** [comment]
input type file is already supported in the latest versions.
