### ISSUE TITLE
How to add multiple files 

### ISSUE THREAD

**Issue by jayDesai89** [georgipeltekov/ngx-file-drop#87]
I want to upload multiple files at the same time but every time i tried to do it , Its just over ride the excising or previously added file.
Is there a way to to accept multiple files at same time?
below is the console of file upload. 
It should work with multiple files. but I am missing something. Please if anyone can help with that. 

Thanks a lot for your time in advanced.

![capture](https://user-images.githubusercontent.com/33063944/43324200-85526b42-9181-11e8-8a3c-265af4cad678.PNG)

**Comment by georgipeltekov** [comment]
Hi, could you please give reproducible example. A stackblitz will be perfectly fine. Basically if you dont want to override the files, just append them to your list, that is attached  to your component, not override them, once you receive the files.

**Comment by jayDesai89** [comment]
I am not able to create stack blitz right now. but I have used excat same code from package. in both .ts and .html. and it is working perfectly fine with just drag and drop. It shows me in console and all good but  when I upload next file. it remove previously added file and shows only current file that I have uploaded. 
I am trying to make stackblitz so that you get better idea, bu thanks for your quick response

**Comment by georgipeltekov** [comment]
Yes, exactly. That is because most probably you are doing something like that in your code:
this.files = event.files;

so every time new drop event occurred you are overriding your data with what is newly dropped.  So you  need to append instead of override in your custom code.

**Comment by jayDesai89** [comment]
this.files = UploadFile.append(event.files); 
 I am kind of new with this , I am not able to get it , Can you elaborate more or can please show me the code ?

**Comment by georgipeltekov** [comment]
You need to use the push command

https://www.tutorialspoint.com/typescript/typescript_array_push.htm

**Comment by jayDesai89** [comment]
push command on what actually ? 
`  public dropped(event: UploadEvent) {
    this.files = event.files;
    this.files.push(); // ??
    console.log(UploadFile);
    console.log(this.files);
    console.log(event.files, 'this is event');
    for (const droppedFile of event.files) {
      // Is it a file?
      if (droppedFile.fileEntry.isFile) {
        const fileEntry = droppedFile.fileEntry as FileSystemFileEntry;
        fileEntry.file((file: File) => {

          // Here you can access the real file
          console.log(droppedFile.relativePath, file);
         //  this.files.push(droppedFile); // This give me garbage value in array 
          console.log(this.files);
          if (this.files.length !== 0) {
            console.log(`There is a file`);
            if (file.type === 'image/png') {
              this.fileType = 'image';
              console.log('This is an Image file.');
            }
          } else if (this.files.length === 0) {
            console.log(`There is no file at all`);
          }
          /**
          // You could upload it like this:
          const formData = new FormData()
          formData.append('logo', file, relativePath)
          // Headers
          const headers = new HttpHeaders({
            'security-token': 'mytoken'
          })
          this.http.post('https://mybackend.com/api/upload/sanitize-and-save-logo', formData, { headers: headers, responseType: 'blob' })
          .subscribe(data => {
            // Sanitized logo returned from backend
          })
          **/

        });
      } else {
        // It was a directory (empty directories are added, otherwise only files)
        const fileEntry = droppedFile.fileEntry as FileSystemDirectoryEntry;
        console.log(droppedFile.relativePath, fileEntry);
      }
    }
  }`

**Comment by georgipeltekov** [comment]
You need to try to think and understand how the things are working, not to hurry to just write some code. In this way you will learn and become better developer. If you search in google: how to append to array in typescript you will find plenty of answers.  This is the key to success - understand what you are doing and how the things are working.  Did you read the article I sent you? 

I think this.files.push(event.files); should do the trick.
