### ISSUE TITLE
Open file browser by clicking the file drop area

### ISSUE THREAD

**Issue by nik10-mah** [georgipeltekov/ngx-file-drop#92]
Hi.
Thank you for this plugin.
I want to add files by click and drop on the file drop area. Is there as way I can do that?

**Comment by akatrukhin** [comment]
If you already installed in your component 'ngx-file-drop',  just add this code there.

In html:
`
<input type="file" #addFiles (change)="onFilesAdded()" multiple />
`

`
@ViewChild('addFiles') addFiles;
  onFilesAdded() {
    const files: File[] = this.addFiles.nativeElement.files;
    for (let i = 0; i < files.length; i++) {
      const file: File = files[i];
      const fakeFileEntry: FileSystemFileEntry = {
        name: file.name,
        isDirectory: false,
        isFile: true,
        file: (callback: (filea: File) => void): void => {
          callback(file);
        }
      };
      const toUpload: UploadFile = new UploadFile(fakeFileEntry.name, fakeFileEntry);
      this.files.push(toUpload); 
    }
  }
`

**Comment by georgipeltekov** [comment]
Thanks @akatrukhin  for the answer
