### ISSUE TITLE
How to get the file type

### ISSUE THREAD

**Issue by robertbelarmin** [georgipeltekov/ngx-file-drop#93]
From input type event, I can get the file type from target.files[0].type which gives me application/pdf

How can I get this type from UploadFile Event..?

**Comment by georgipeltekov** [comment]
You can check the readme file. Basically first you need to read the file:

```
 fileEntry.file((file: File) => {
          // Here you can access the real file
          console.log(droppedFile.relativePath, file);
});

```
and you will have all the needed data
