### ISSUE TITLE
adjust style

### ISSUE THREAD

**Issue by marriskleinert** [georgipeltekov/ngx-file-drop#95]
Hi, it's me again.
Via the customstyle attribute I can adjust the style for the div with the id 'dropZone'...
But the div inside with the class 'content' will still have the height 100px.
The 'over' class will also still have the background-color which I don't want...

**Comment by georgipeltekov** [comment]
But this is just a matter of proper css. You can check here:
https://stackblitz.com/edit/angular-xbnl3j

I changed the background color, but in the same way you can remove it or add any addition css changes you want
