### ISSUE TITLE
Check for file extension while onFileOver

### ISSUE THREAD

**Issue by marriskleinert** [georgipeltekov/ngx-file-drop#96]
I'm trying to verify the file extensions of the dragged files.
The onFileOver sends a DragEvent but there are no files in it.,, There should be files of the type 'File' in it though...

Any suggestions?

![image](https://user-images.githubusercontent.com/28430291/46861422-f5995500-ce12-11e8-88e7-5dec7d27baa8.png)

**Comment by georgipeltekov** [comment]
check in the readme file how the files are retrieved and printed to the console.
Basically you need to call fileEntry.file to get the file.

**Comment by georgipeltekov** [comment]
aa I got your point. Unfortunately you cannot do this, as this is restricted due to security purposes (not connected with the library)
https://stackoverflow.com/questions/25016442/how-to-distinguish-if-a-file-or-folder-is-being-dragged-prior-to-it-being-droppe

**Comment by marriskleinert** [comment]
Okay, thank you anyway! 👍
